### DISCUSSION TITLE
[cloudformation] Error parsing parameter '--template-body': Unable to load paramfile

### DISCUSSION THREAD

**Discussion by santosh** [aws/aws-cli#7245] [Q&A] [answered]
I am following basic cloudformation tutorial. This is my template contents:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Description: A simple EC2 instance
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-006d3995d3a6b963b
      InstanceType: t2.micro
      KeyName: dev-on-ec2
```

A key with that name already exists in the AWS account. 

I am running this command:

```
aws cloudformation create-stack --stack-name ec2-demo --template-body file:///tmp/cfn/ec2.yaml
```

Location of the template is: `/tmp/cfn/ec2.yaml`

I am getting this error:

Error parsing parameter '--template-body': Unable to load paramfile file:///tmp/cfn/ec2.yaml: [Errno 2] No such file or directory: '/tmp/cfn/ec2.yaml'
