### DISCUSSION TITLE
NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed

### DISCUSSION THREAD

**Discussion by yoshidakoutarou** [aws/aws-cli#8140] [Q&A]
Below is the version of the tool used.

```
➤ sam --version
SAM CLI, version 1.95.0
➤ node -v
v20.5.1
```

I am currently trying to build a Lambda using Layer.

I tried to build using aws-sam-cli, but Esbuild gave me an error importing layers.

```
{'BuildMethod': 'esbuild', 'BuildProperties': {'Minify': True, 'Target': 'es2022', 'Sourcemap': True, 'EntryPoints': ['app/app.ts']}}        
architecture: x86_64 functions: TestFunction                                                                                   
Running NodejsNpmEsbuildBuilder:CopySource                                                                                                   
Running NodejsNpmEsbuildBuilder:NpmInstall                                                                                                   
Running NodejsNpmEsbuildBuilder:EsbuildBundle                                                                                                

Build Failed
Error: NodejsNpmEsbuildBuilder:EsbuildBundle - Esbuild Failed: ✘ [ERROR] Could not resolve "/opt/nodejs/dist/db"

    app/app.ts:6:19:
      6 │ import { Db } from '/opt/nodejs/dist/db';
        ╵                    ~~~~~~~~~~~~~~~~~~~~~

1 error
```

The Lambda template.yaml can be found here.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
    test

Parameters:
    Prefix:
        Type: String
        Default: '__PREFIX__'

Globals:
    Function:
        Runtime: nodejs18.x
        Timeout: 10
        MemorySize: 128
    Api:
        OpenApiVersion: 3.0.1

Resources:
    TestFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: !Sub '${Prefix}-test'
            CodeUri: ../src
            Handler: app.lambdaHandler
            Architectures:
                - x86_64
            Layers:
                - !ImportValue MysqlLayer
            Role: !GetAtt TestFunctionRole.Arn

        Metadata:
            BuildMethod: esbuild
            BuildProperties:
                Minify: true
                Target: 'es2022'
                Sourcemap: true
                EntryPoints:
                    - app/app.ts

    TestFunctionRole:
        ...

```

Information on tsconfig.json can be found here.

```
{
    "compilerOptions": {
        "target": "es2022",
        "strict": true,
        "preserveConstEnums": true,
        "noEmit": true,
        "sourceMap": false,
        "module": "commonjs",
        "moduleResolution": "node",
        "esModuleInterop": true,
        "skipLibCheck": true,
        "forceConsistentCasingInFileNames": true
    },
    "exclude": ["node_modules", "**/*.test.ts"]
}
```

I heard that setting External may solve the problem, but when I actually set it, the build error was resolved, but the Lambda stopped working with an error.

```
External:	
　　- '/opt/nodejs/dist/*'
```

After reviewing the error, my sense is that the module on the layer side has not been resolved.

```
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'mysql2/promise'\nRequire stack:\n- /opt/nodejs/dist/db/index.js\n- /var/task/app.js\n- /var/runtime/index.mjs",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'mysql2/promise'",
        "Require stack:",
        "- /opt/nodejs/dist/db/index.js",
        "- /var/task/app.js",
        "- /var/runtime/index.mjs",
        "    at _loadUserApp (file:///var/runtime/index.mjs:1061:17)",
        "    at async UserFunction.js.module.exports.load (file:///var/runtime/index.mjs:1093:21)",
        "    at async start (file:///var/runtime/index.mjs:1256:23)",
        "    at async file:///var/runtime/index.mjs:1262:1"
    ]
}
```

The directory structure is shown here.

```
.
├── README.md
└── business
    ├── nodeLayer
    │   └── db
    │       ├── cf
    │       │   ├── samconfig.toml
    │       │   └── template.yaml
    │       ├── dist
    │       │   └── db
    │       │       ├── index.js
    │       │       ├── index.js.map
    │       │       ├── testDb.js
    │       │       └── testDb.js.map
    │       ├── jest.config.ts
    │       ├── package-lock.json
    │       ├── package.json
    │       ├── src
    │       │   ├── index.ts
    │       │   └── testDb.ts
    │       └── tsconfig.json
    ├── testFunc
    │   ├── cf
    │   │   ├── samconfig.toml
    │   │   └── template.yaml
    │   └── src
    │       ├── README.md
    │       ├── app
    │       │   └── app.ts
    │       ├── jest.config.ts
    │       ├── package-lock.json
    │       ├── package.json
    │       └── tsconfig.json
```

I would like to know how to solve this problem aleva.

**Comment by tim-finnigan** [comment]
It looks like this question was intended for the AWS SAM CLI rather than the AWS CLI. Here is where you can open a discussion: https://github.com/aws/aws-sam-cli/discussions

**Comment by github-actions** [comment]
Hello! Reopening this discussion to make it searchable.

**Comment by rrrokhtar** [comment]
Adding the packages those included on the layer as external will resolve that

**External: !Split [" ", !Ref ExternalDependencies]** inside Metadata's BuildProperties while having it on parameter so that if you need it in multiple functions just one line will do that
```yml
Parameters:
  ExternalDependencies:
    Type: String
    Default: "mysql2 better-sqlite3 oracledb mysql tedious pg-query-stream sqlite3"

Resources
  someFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ....
      Handler: ....
      Role: ....
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        ....
        External: !Split [" ", !Ref ExternalDependencies]
        ....
```
Replace the default value with your packages want to exclude
