### ISSUE TITLE
MalformedManifestException with CreateJob for import

### ISSUE THREAD

**Issue by edrozenberg** [aws/aws-cli#1298]
Using valid import manifests I'm getting MalformedManifestException running aws cli under Slackware Linux. Tried various versions of aws cli - 1.7.21, 22, 23.

Something else I tried -  I used the CloudBerry S3 tool to successfully generate an import job. I then took that same manifest used by CloudBerry and got MalformedManifestException when using aws cli.

I submitted a tech support case to AWS - they used the same manifest and it was OK on aws cli under Windows, but they got the same error as me when running aws cli under Amazon Linux. So it could be related to character sets or line endings in some way.

Manifest:
```
manifestVersion: 2.0
bucket: aws-import-20150410-items
logBucket: aws-import-20150410-logs
deviceId: mydevice
generator: Myself
returnAddress:
   name: Myname
   company: Mycompany
   street1: Mystreet
   city: Mycity
   stateOrProvince: NY
   postalCode: 12345
   phoneNumber: 123-456-7890
   country: USA
eraseDevice: yes
notificationEmail: myemail@test.com;otheremail@test.com
serviceLevel: standard
```

Command:

    aws importexport create-job --job-type import --manifest /root/Downloads/aws-import-20150407-manifest.txt --validate-only

Result:

    A client error (MalformedManifestException) occurred when calling the CreateJob operation: Your manifest is not well-formed
