### ISSUE TITLE
aws cloudformation package command will not output JSON despite documentation

### ISSUE THREAD

**Issue by TomDunn** [aws/aws-cli#2308]
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-cli-package.html

Indicates that I should be able to generate a JSON-formatted cloudformation template. I have a template that is already in JSON as follows:

```json
{
  "AWSTemplateFormatVersion" : "2010-09-09",
  "Transform" : "AWS::Serverless-2016-10-31",

  "Resources": {

    "ApiLambdaFunc": {
      "Type" : "AWS::Lambda::Function",
      "Properties" : {
        "Code": "./",
        "Description": "foo bar",
        "FunctionName": "foo",
        "Handler": "index.handler",
        "MemorySize": "128",
        "Runtime": "nodejs4.3",
        "Timeout": "2"
      }
    }
  }
}
```
Then I run:
```sh
aws cloudformation package --s3-bucket <<REDACTED>> --template cloudformation/template.json --output-template-file foo.json
```

But then foo.json is yaml:
```yml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ApiLambdaFunc:
    Properties:
      Code:
        S3Bucket: <<REDACTED>
        S3Key: <<REDACTED>>
      Description: foo bar
      FunctionName: foo
      Handler: index.handler
      MemorySize: '128'
      Runtime: nodejs4.3
      Timeout: '2'
    Type: AWS::Lambda::Function
Transform: AWS::Serverless-2016-10-31
```
I've also tried command of the form (as shown on docs page):
```sh
 aws cloudformation package --s3-bucket <<REDACTED>> --template cloudformation/template.json --output json
```
aws cli version: aws-cli/1.11.24 Python/2.7.12 Linux/4.4.0-51-generic botocore/1.4.81

I installed using instructions from:
http://docs.aws.amazon.com/cli/latest/userguide/installing.html#install-bundle-other-os
