### ISSUE TITLE
cloudformation package generates S3BodyLocation by default

### ISSUE THREAD

**Issue by dtimberlake** [aws/aws-cli#2320]
# Introduction

`aws cloudformation package` currently creates `S3BodyLocation` for `AWS::ApiGateway::RestApi` even when no swagger file is specified in the `S3BodyLocation` property. The default action is to zip the entire working directory and upload it to S3. 

Since this this parameter is not required (you can specify an inline `Body` or just use other resources to specify your api), I believe this should only run when you explicitly specify a swagger file.

# Reproduce

## 1. Create initial template
```yaml
# template.yml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
        Name: !Ref AWS::StackName
```

## 2. Package code (this will zip your entire current directory and upload)
```
aws cloudformation package \
  --template-file template.yml \
  --s3-bucket <bucket> \
  --output-template-file package-template.yml
```
This generate `package-template.yml`
```yaml
Resources:
  RestApi:
    Properties:
      BodyS3Location:
        Bucket: <bucket>
        Key: <key>
      Name:
        Ref: AWS::StackName
    Type: AWS::ApiGateway::RestApi
```

# Workaround

Remove `BodyS3Location` once the template has been created and remove the uploaded artifact from S3. Can't do anything about the cost associated with the initial upload.
