### ISSUE TITLE
cloudformation describe-stacks result does not include exported names

### ISSUE THREAD

**Issue by talentedmrjones** [aws/aws-cli#2637]
This was discovered on awscli version aws-cli/1.11.97 Python/2.7.10 Darwin/16.6.0 botocore/1.5.60

The following template contains output with  **exported names**

```
AWSTemplateFormatVersion: "2010-09-09"
Description: "VPC with exports"

Resources:
  Vpc:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: True
      EnableDnsHostnames: True

Outputs:
  VpcId:
      Description : "VPC ID"
      Value:  !Ref Vpc
      Export:
        Name: !Sub ${AWS::StackName}-VpcId
```

Running `aws cloudformation describe-stacks` will include the outputs, but **not** the Export Name.

```
...
 "Outputs": [
                {
                    "Description": "VPC ID", 
                    "OutputKey": "VpcId", 
                    "OutputValue": "vpc-68e4ff0f"
                }
            ]
...
```

With `--debug` you can see the exported names in the response body XML:

```
2017-06-04 18:13:54,142 - MainThread - botocore.parsers - DEBUG - Response body:
<DescribeStacksResponse xmlns="http://cloudformation.amazonaws.com/doc/2010-05-15/">
  <DescribeStacksResult>
    <Stacks>
      <member>
        <Outputs>
          <member>
            <Description>VPC ID</Description>
            <ExportName>test-network-VpcId</ExportName>
            <OutputKey>VpcId</OutputKey>
            <OutputValue>vpc-68e4ff0f</OutputValue>
          </member>

        </Outputs>
...
```
