### ISSUE TITLE
Unrecognized resource types: CognitoUserPool, CognitoUserPoolClient

### ISSUE THREAD

**Issue by ikim23** [aws/aws-cli#2684]
I wanted to deploy my CF stack via Serverless framework, but I received exception. So I validated CF config via aws-cli and it respond with ValidationError.
```
Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: test-pool
  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: test-client
      ExplicitAuthFlows:
        - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
      UserPoolId:
        Ref: CognitoUserPool
```
```
aws cloudformation validate-template --template-body file://test-template.yml
```
```
An error occurred (ValidationError) when calling the ValidateTemplate operation: Template format error: Unrecognized resource types: [AWS::Cognito::UserPool, AWS::Cognito::UserPoolClient]
```
It was strange because I was sure that CF configuration was correct and I was able to deploy it before on my old machine. I fought that it can be bug in the new 1.11.113 version, so I tried it on my old machine and it worked like a charm on 1.11.84. However, when I reinstalled 1.11.113 to older 1.11.84 the error message remained. Please, can you tell me what I am doing wrong?. Thank you.
