### ISSUE TITLE
aws package incorrectly parses "!GetAtt VPC.Outputs.VpcId"

### ISSUE THREAD

**Issue by romaninsh** [aws/aws-cli#2719]
As per documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-getatt.html , this is a valid code:

``` yml
    Parameters:
        VpcId: !GetAtt VPC.Outputs.VpcId
```

When this is parsed by `aws package` it is converted into:

``` yml
      Parameters:
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs
          - VpcId
```

Which is invalid, because GetAtt supports only two arguments producing error:

"every Fn::GetAtt object requires two non-empty parameters, the resource name and the resource attribut"

The expected output is:

``` yml
      Parameters:
        VpcId:
          Fn::GetAtt:
          - VPC
          - Outputs.VpcId
```
