### ISSUE TITLE
Generalize package functionality

### ISSUE THREAD

**Issue by thinkerbot** [aws/aws-cli#2862]
I've found uses for packaging local artifacts in a variety of places that are unsupported by (and/or somewhat unrelated to) the `aws cloudformation package` command as it stands, for example:

* uploading files for cfn-init
* uploading docker images 

It's lead me to think about how you could generalize, make extensible, and possibly simplify packaging. 

## Proposal

Declare artifacts in template Metadata, add resulting s3 attributes as default values on parameters. 

### Example

Before:

```yaml
Metadata:
  AWS::Cloudformation::Package:
    MyArtifact:
       ArtifactType: s3
       ParameterMapping:
         MyS3Bucket: BucketName
         MyS3Path: Path
         MyS3URL: Url
       Properties:
         BucketName: bucketname
         PathPrefix: prefix
         LocalPath: ./path/to/dir_or_file
Parameters:
    MyS3Bucket:
      Type: String
    MyS3Path:
      Type: String
    MyS3URL:
      Type: String
Resources:
# Use Ref as needed
```

After:

```yaml
# ...
Parameters:
    MyS3Bucket:
      Type: String
      Default: bucketname
    MyS3Path:
      Type: String
      Default: prefix/CHECKSUM
    MyS3URL:
      Type: String
      Default: https://s3.amazonaws.com/bucketname/prefix/CHECKSUM
# ...
```

### Rationale

From a code perspective this ends up being easy; you don't have to support fields within specific resources. You simply look under the metadata, zip as needed, upload, and save the result as a parameter default. Then leave it to the user to use it wherever it is needed.  As a technical detail you'd have to support mapping S3 attributes since various forms of the S3 bucket/path/url are needed across resource types. 

This approach would make packaging possible anywhere an s3 artifact can be used, including places where the s3 URL needs to be interpolated.  It is inherently forward compatible with all resource types that may be added in the future. I imagine it wouldn't be too hard to make it backwards compatible with the existing package behavior.  

Lastly I think it establishes a pattern for the general problem of "upload a local artifact". Extending the pattern to non-s3 artifacts like docker containers would be a matter of adding new artifact types. 

### Variations

One obvious variation would be to simply print out the parameter values rather than rewriting the template. Personally I like that approach as it would make packaging a transparent extension to a template, much like the use of Metadata for cfn-init. It would also solve issues that arise in rewriting, like #2757.

**Comment by joguSD** [comment]
@sanathkr thoughts?

**Comment by sanathkr** [comment]
This is an interesting approach. I really like the idea of exposing the values as parameters with default values. But I am not too inclined with the Metadata approach: Bucket, Key & Paths might be specific to the person deploying. Each developer might want to deploy to their own favorite bucket. Dev & Prod stacks want to use a different bucket. Now you have to edit the template every time to change the buckets & prefixes.  

Instead, I think it might make sense to keep this separate like a `.package-config.yaml` file. Something external to the CFN template so different users can have different preferences. Thoughts?

**Comment by thinkerbot** [comment]
I hadn't thought about the way this would work for that use case, but you're right.  Might be a separate file really is the best way to do this -- kinda elegant to do it that way.  In that case packaging is a parameter assembly step.   You wouldn't even need write the output values into the template; they could be passed in just like any other parameter.

**Comment by thinkerbot** [comment]
I've been experimenting with this a little.  Seems like if the `Metadata` section only declares the local paths then the buckets and prefixes can continue to be passed in from the command line.  I have a branch that does this but it doesn't have unit tests so it's not ready for a PR.  I'm also fairly green at python so I wanted to see how it looks to you before I endeavor to add the tests :)

 * https://github.com/thinkerbot/aws-cli/tree/generalize_package_functionality

As an example of how it looks in practice, see below.

```bash
# Make an example dir
mkdir lib
touch lib/index.py

# Make an example file
touch example_file.txt

# Make a template, noting how the parameters can be used in arbitrary places.
cat > template.yml <<DOC
Metadata:
  AWS::CloudFormation::Package:
    Parameters:
      ArtifactsBucket:
        Type: S3Bucket
      Source:
        Type: File
        Properties:
          Path: ./example_file.txt
          Format: https_url
      Code:
        Type: Zipfile
        Properties:
          Path: ./lib
          Format: key

Parameters:
  ArtifactsBucket:
    Type: String

  Code:
    Type: String

  Source:
    Type: String

Resources:

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: ArtifactsBucket
        S3Key:
          Ref: Code

  Ec2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            /tmp/example:
              source:
                Ref: Source
DOC
```

Now package:

```bash
bucket="s3-bucket-name"
aws cloudformation package --s3-bucket "$bucket" --template-file template.yml
```

The output ends up like this:

```yaml
Metadata:
  AWS::CloudFormation::Package:
    Parameters:
      ArtifactsBucket:
        Type: S3Bucket
      Code:
        Properties:
          Format: key
          Path: ./lib
        Type: Zipfile
      Source:
        Properties:
          Format: https_url
          Path: ./example_file.txt
        Type: File
Parameters:
  ArtifactsBucket:
    Default: s3-bucket-name
    Type: String
  Code:
    Default: 7291889c90b5659329f6e5a0d4d7baf1
    Type: String
  Source:
    Default: https://s3.amazonaws.com/s3-bucket-name/d41d8cd98f00b204e9800998ecf8427e
    Type: String
Resources:
  Ec2Instance:
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            /tmp/example:
              source:
                Ref: Source
    Type: AWS::EC2::Instance
  LambdaFunction:
    Properties:
      Code:
        S3Bucket:
          Ref: ArtifactsBucket
        S3Key:
          Ref: Code
    Type: AWS::Lambda::Function
```
