### ISSUE TITLE
v1.11.178: `cloudformation package`, when given a YAML template, converts even explicit strings to integers when the string begins with a 0 and contains nothing but digits

### ISSUE THREAD

**Issue by niels** [aws/aws-cli#2934]
In `aws-cli/1.11.178 Python/3.6.3 Linux/4.13.9-1-ARCH botocore/1.7.36`, given a `template.yaml`

```yaml
AWSTemplateFormatVersion: 2010-09-09

Mappings:
  Regions:
    eu-central-1:
      ELBAccountID: '054676820928'
    us-east-2:
      ELBAccountID: "033677994240"
    us-west-1:
      ELBAccountID: !!str 027434742980

Resources:
  AccessLogsS3Bucket:
    Type: AWS::S3::Bucket

  AccessLogsS3BucketPolicy:
    DependsOn: AccessLogsS3Bucket
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref AccessLogsS3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Action:
              - s3:PutObject
            Effect: Allow
            Resource: !Sub "arn:aws:s3:::${AccessLogsS3Bucket}/AWSLogs/${AWS::AccountId}/*"
            Principal:
              AWS: !Join [":", ["arn:aws:iam:", !FindInMap [Regions, !Ref "AWS::Region", ELBAccountID], "root"]]
```

when running

```bash
aws \
  --region eu-central-1 \
  cloudformation package \
    --template-file ./template.yaml \
    --s3-bucket cf-templates
```

the resulting (i.e. packaged / uploaded to S3) template has all string castings for strings *which contain nothing but digits and begin with a zero* in the `Mappings` removed:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Mappings:
  Regions:
    eu-central-1:
      ELBAccountID: 054676820928
    us-east-2:
      ELBAccountID: 033677994240
    us-west-1:
      ELBAccountID: 027434742980
Resources:
  AccessLogsS3Bucket:
    Type: AWS::S3::Bucket
  AccessLogsS3BucketPolicy:
    DependsOn: AccessLogsS3Bucket
    Properties:
      Bucket:
        Ref: AccessLogsS3Bucket
      PolicyDocument:
        Statement:
        - Action:
          - s3:PutObject
          Effect: Allow
          Principal:
            AWS:
              Fn::Join:
              - ':'
              - - 'arn:aws:iam:'
                - Fn::FindInMap:
                  - Regions
                  - Ref: AWS::Region
                  - ELBAccountID
                - root
          Resource:
            Fn::Sub: arn:aws:s3:::${AccessLogsS3Bucket}/AWSLogs/${AWS::AccountId}/*
        Version: 2012-10-17
    Type: AWS::S3::BucketPolicy
```

This can lead to many problems down the road. In the specific use case above, I was trying to create a bucket policy for ELB access logs in the eu-central-1 region which failed with an `Invalid principal in policy` error due to the principal being set to `arn:aws:iam::5.4676820928E10:root` rather than `arn:aws:iam::054676820928:root`.

(I have worked around this by storing the entire `arn:…:root` string in the `Mappings`.)

**Comment by dstufft** [comment]
Tagging this as an enhancement for the cloudformation package command. This is going to be a bit tricky because PyYaml doesn't provide an easy way to preserve these. One option could be to switch to using ruammel.yaml which does, but that defaults to YAML 1.2 instead of 1.1 so that might be backwards incompatible. Otherwise it's going to requir digging into PyYAML's representers layer to override it's behavior on ``str``.

**Comment by shortjared** [comment]
For those that get caught with this, you can also do a bit of a hack like this to get things working.

```
      Value: !Join [ "", [ "0", "12345678910" ] ]
```

Clearly not great, but it'll do.

**Comment by ben-elsen** [comment]
Hello,  is there some progress regarding this issue?

**Comment by lmayorga1980** [comment]
I have the following template but I am unable to do a FindInMap lookup with a leading zero.

```json
{
    "AWSTemplateFormatVersion": "2010-09-09",
    "Transform": "AWS::Serverless-2016-10-31",
    "Mappings": {
        "NotifictionTopicArn": {
            "012811112209": {
                "Arn": "arn:aws:sns:us-east-1:012811112209:MyTopic"
            },
            "52905555765": {
                "Arn": "arn:aws:sns:us-east-1:52905555765:MyTopic"
            }
        }
    },
    "Globals": {
        "Function": {
            "Timeout": 60
        }
    },
    "Resources": {
       ...
        "SomeRole": {
            "Type": "AWS::IAM::Role",
            "Properties": {
                "Path": "/my_uservices/",
                "RoleName": "SomeRole",
                "AssumeRolePolicyDocument": {
                    "Version": "2012-10-17",
                    "Statement": [
                        {
                            "Effect": "Allow",
                            "Principal": {
                                "Service": [
                                    "lambda.amazonaws.com",
                                    "events.amazonaws.com"
                                ]
                            },
                            "Action": "sts:AssumeRole"
                        }
                    ]
                },
                "Policies": [
                    {
                        "PolicyName": "CM-Lambda-Policy",
                        "PolicyDocument": {
                            "Version": "2012-10-17",
                            "Statement": [
                                {
                                    "Effect": "Allow",
                                    "Action": [
                                        "logs:CreateLogGroup",
                                        "logs:CreateLogStream",
                                        "logs:PutLogEvents"
                                    ],
                                    "Resource": "arn:aws:logs:*:*:log-group:/aws/lambda/*:*:*"
                                },
                                {
                                    "Effect": "Allow",
                                    "Action": [
                                        "ec2:ModifyImageAttribute",
                                        "ec2:DescribeImages",
                                        "ec2:DescribeImageAttribute"
                                    ],
                                    "Resource": "*"
                                },
                                {
                                    "Effect": "Allow",
                                    "Action": [
                                        "sns:ListTagsForResource",
                                        "sns:TagResource",
                                        "sns:ListSubscriptionsByTopic",
                                        "sns:Publish",
                                        "sns:GetTopicAttributes"
                                    ],
                                    "Resource": {
                                        "Fn::FindInMap": [
                                            "NotifictionTopicArn",
                                             { "Ref": "AWS::AccountId" }
                                            ,
                                            "Arn"
                                        ]
                                    }
                                }
                            ]
                        }
                    }
                ]
            }
        },
     ...
```

Any workarounds for this scenario.

**Comment by stealthycoin** [comment]
Looks like this was fixed in CLI V2 by switching to ruamel from pyyaml. I tried this using the newest version 2.0.7 which translated the mapping into:

```yaml
Mappings:
  Regions:
    eu-central-1:
      ELBAccountID: '054676820928'
    us-east-2:
      ELBAccountID: '033677994240'
    us-west-1:
      ELBAccountID: '027434742980'
```

All quoted. I am going to mark this as resolved, we don't plan to change that dependency in V1 of the CLI since it is a breaking change, and the point of CLI V2 was to be able to make changes like this. If you are worried about this behavior I would recommend switching to CLI V2.
