### ISSUE TITLE
eb produces no output on some machines

### ISSUE THREAD

**Issue by ianseyer** [aws/aws-cli#3028]
I am attempting to use `awsebcli` to deploy my code from gitlab to beanstalk.

On another project, the script works fine deploying to a different AWS account. I am attempting to deploy to a new application in a new AWS account.

The gitlab script looks like this:

```
deploy-develop:
  stage: deploy
  image: python:3.6
  variables:
    BUILD_ENV: 'dev'
  script:
    - pip install awsebcli
    - eb init
    - eb list
    - eb -v status
    - eb
```

and produces this output:

```
$ eb init
$ eb list
$ eb -v status
$ eb
Job succeeded
```
None of the `eb` commands are producing any output. I am able to reproduce this on my local machine. However, if I execute it within the same docker image (`python:3.6`) it produces the expected output.

I can even try to execute `eb garbage` and it throws nothing to STDOUT/STDERR.

I have tried with multiple credentials and no credentials to no avail. I have also tried installing via `pip` and `pip3`.

I would give version information, but I can't.

`which eb` produces `/Users/iseyer/.pyenv/shims/eb` on OSX and `/usr/local/bin/eb` in the runner.

UPDATE:

I figured out that changing the `.elasticbeanstalk/config.yml` file resolves this issue, however this should still throw an error as I do not understand why this would be an issue.

Working config:
```
branch-defaults:
  develop:
    environment: develop
  master:
    environment: prod
deploy:
  artifact: Archive.zip
environment-defaults:
  develop:
    branch: null
    repository: null
  prod:
    branch: null
    repository: null
global:
  application_name: redacted
  default_ec2_keyname: redacted
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Multi-container Docker
    running on 64bit Amazon Linux/2.7.5
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
```

Non working config:
```
branch-defaults:
deploy:
  artifact: archive.zip
environment-defaults:
  redacted-develop:
      branch: null
    repository: null
global:
  application_name: redacted
  default_ec2_keyname: ops
  default_platform: arn:aws:elasticbeanstalk:us-east-1::platform/Multi-container Docker
    running on 64bit Amazon Linux/2.7.5
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
```
