### ISSUE TITLE
cannot find platform tomcat8-java8

### ISSUE THREAD

**Issue by agusvazquez** [aws/aws-cli#3134]
Hello guys!

I "developed" some Continous integration in bitrise using the following commands.

Everything worked fine yesterday in all of my apps. But today is failing with this message on the "eb init" call.

ERROR: NotFoundError - The EB CLI cannot find a platform for key "tomcat8-java8".

my shell is this one

pip install awsebcli

```
export AWS_ACCESS_KEY_ID=XXXX
export AWS_SECRET_ACCESS_KEY=YYY

eb init -p tomcat8-java8
eb deploy
```

my config.yml is this one.

```
 branch-defaults:
   master:
     environment: environment
     group_suffix: null
 deploy:
   artifact: build/libs/src-1.0.0.jar
 global:
   application_name: AppName
   default_ec2_keyname: null
   default_platform: tomcat8-java8
   default_region: us-west-2
   include_git_submodules: true
   instance_profile: null
   platform_name: null
   platform_version: null
   profile: null
   sc: git
   workspace_type: Application
```

How can i make it work?

Thanks!
