### ISSUE TITLE
aws cloudformation update-stack throws "No updates are to be performed" even if there is update

### ISSUE THREAD

**Issue by KarlisJ** [aws/aws-cli#3249]
```
aws cloudformation update-stack --stack-name LP-web-15 --use-previous-template --parameters \
                ParameterKey=ImageVersion,ParameterValue=$CIRCLE_SHA1 \
                ParameterKey=KeyName,UsePreviousValue=true \
                ParameterKey=HealthCheckPath,UsePreviousValue=true \
                ParameterKey=DesiredCount,UsePreviousValue=true \
                ParameterKey=EnvAppKey,UsePreviousValue=true \
                ParameterKey=EnvAwsKey,UsePreviousValue=true \
                ParameterKey=EnvAwsSecret,UsePreviousValue=true \
                ParameterKey=EnvBugsnagAppKey,UsePreviousValue=true \
                ParameterKey=EnvDbPassword,UsePreviousValue=true \
                ParameterKey=EnvDbUsername,UsePreviousValue=true 
```
where $CIRCLE_SHA1 does return new image id that is previously pushed to ECR. Given commands returns 

`An error occurred (ValidationError) when calling the UpdateStack operation: No updates are to be performed.`

If I update the stack manually then the update is successful.

Inside the stack's template 

```
EcsTd:
    Type: AWS::ECS::TaskDefinition
    DependsOn: LogGroup
    Properties:
      Family: !Sub ${EnvironmentName}-${PlatformName}-${Environment}
      ContainerDefinitions:
      - Name: !Sub ${EnvironmentName}-${PlatformName}-${Environment}
        Image: !Sub ${AWS::AccountId}.dkr.ecr.us-east-1.amazonaws.com/${PlatformName}:${ImageVersion}
...
```
