### ISSUE TITLE
Unrecognized resource types: [AWS::Cloud9::EnvironmentEC2]

### ISSUE THREAD

**Issue by jarnohenneman** [aws/aws-cli#3403]
Unable to run the following command:
```
aws cloudformation validate-template --template-body file://out/cloud9.json

aws --version
aws-cli/1.15.45 Python/2.7.13 Linux/4.4.0-1060-aws botocore/1.10.45
```

snippet of cloud9.json
```
"Resources": {
    "Environment": {
      "Properties": {
        "AutomaticStopTimeMinutes": 30,
        "InstanceType": "t2.micro",
        "Name": "IDE",
        "OwnerArn": {
          "Ref": "OwnerArn"
        },
        "Repositories": [

        ]
      },
      "Type": "AWS::Cloud9::EnvironmentEC2"
    }
  }
```

**Comment by JordonPhillips** [comment]
I was not able to reproduce this in `us-west-2`. What region are you in? It could be that the resource is not available in that region yet. Here's what I tried:

```yaml
Parameters:
  SubnetId:
    Type: String
Resources:
  C9IDE:
    Properties:
      InstanceType: t2.micro
      Name: IDE
      SubnetId: !Ref 'SubnetId'
    Type: AWS::Cloud9::EnvironmentEC2
```
