### ISSUE TITLE
Add `cloudformation package` support for AWS::Glue::Job resource type

### ISSUE THREAD

**Issue by ilyasotkov** [aws/aws-cli#3570]
Instead of having to upload Glue scripts to S3 manually, it would be nice if it could be done with `aws cloudformation package` command the same way it's done for `AWS::CloudFormation::Stack` or `AWS::Lambda::Function` resource types:

```yaml
Resources:
  MyGlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: MyGlueJob
      Command:
        ScriptLocation: ./gluescript.scala
        Name: glueetl
        ...
```
