### ISSUE TITLE
cloudformation package might upload artifacts multiple times

### ISSUE THREAD

**Issue by Dunedan** [aws/aws-cli#3585]
A CloudFormation template which defines multiple `AWS::Serverless::Function` resources, which use the same artifacts, causes the artifacts to be uploaded multiple times when using `aws cloudformation package --force-upload`. Apparently for each AWS Lambda function using the artifact it's uploaded all over again to the same S3 key.

So e.g. the following template would upload the artifact three times when running the package command with `--force-upload`:
```yaml
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.

Globals:
  Function:
    Runtime: python3.6
    Handler: index.handler

Resources:
  HelloWorld1:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: src/
  HelloWorld2:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: src/
  HelloWorld3:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: src/
```

That's not really noticable for small artifacts, but is annoying with larger artifacts and a lot of `AWS::Serverless::Function` resources using the same artifact.
