### ISSUE TITLE
EKS update-kubeconfig alias

### ISSUE THREAD

**Issue by Artemu** [aws/aws-cli#3638]
The current version of `aws eks update-kubeconfig` is creating the name of the context as an ARN.
Instead passing through an alias flag would eliminate the need to edit the kube config after generating.

**Example of current file generated**
```
- context:
    cluster: arn:aws:eks:eu-west-1:xxxxxxxxxxxx:cluster/eks-staging
    user: arn:aws:eks:eu-west-1:xxxxxxxxxxxx:cluster/eks-staging
  name: arn:aws:eks:eu-west-1:xxxxxxxxxxxx:cluster/eks-staging
```

**With flag if alias was present**
```
$ aws eks update-kubeconfig --name eks-staging --profile development --alias eks-staging
```

**Example of flag output**
```
- context:
    cluster: arn:aws:eks:eu-west-1:xxxxxxxxxxxx:cluster/eks-staging
    user: arn:aws:eks:eu-west-1:xxxxxxxxxxxx:cluster/eks-staging
  name: eks-staging
```
_Mostly the alias to switch in kubectl is the key issue; so using arn's for cluster and user are still plausible._
