### ISSUE TITLE
files included by the include transform are not properly exported by the cloudformation package command

### ISSUE THREAD

**Issue by rianwouters** [aws/aws-cli#3708]
Allthough local files are not uploaded to s3 as well, the included files are not (recursively) exported

Therefore:
* using !Ref, !Sub etc. does not work
* file references are not exported to s3

**Comment by rianwouters** [comment]
very similar to https://github.com/aws/aws-cli/issues/2513

**Comment by rianwouters** [comment]
It's not difficult but also not straightforward to fix as you need to keep track of the level of included and  some contextual info.

* If the include is a direct child of the Resources section, it can almost be handled as CloudFormationStackResource, using { Resources:  <included_dict> }
* If the include is a child of a subpath of the Resources section, it can be handled as 
CloudFormationStackResource, using { Resource: <path> : <included_dict>}

so in general exporting it like CloudFormationStackResource is doing using the correct path will do the job.

**Comment by justnance** [comment]
@rianwouters - Thanks for reaching out.  I agree this is related to #2513 and I'm ready to label your issue as a duplicate or a bug yet. I'll mark it as a feature request pending further review. 

@sanathkr and @kyleknap - what are your thoughts ?

**Comment by rianwouters** [comment]
@sanathkr 
> Sorry I don’t quite understand what the bug is. Can you explain with an example?

See the following example:

template.yml
```
AWSTemplateFormatVersion: '2010-09-09'
Description: Include transform test
Fn::Transform:
  Name: AWS::Include
  Parameters:
    Location: included.yml # correctly exported and uploaded by cfn package
```
included.yml:
```
Parameters:
  TemplateURL:
    Type: String
    Default: nested.yml
Resources:
  IncludedResource:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: nested.yml # NOT EXPORTED AND UPLOADED TO S3 BY CFN PACKAGE
  IncludedResource2:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref TemplateURL # NOT INTERPOLATED TO LONG FORM BY CFN PACKAGE
```
nested.yml:
```
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  NestedResource:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: nestedBucket
```
