### ISSUE TITLE
cloudformation package uses a different root directory for include locations and CodeUri

### ISSUE THREAD

**Issue by ctrey** [aws/aws-cli#3786]
### Issue

When using `aws cloudformation package` on an template that contains files in places such as a AWS::Serverless::Function CodeUri property and an AWS::Include Location property, the package command uses different directories. In the case of the CodeUri, a relative path starts from the location of the template.yaml file. However, the Location parameter on an AWS::Include uses the directory the command is executed from for the relative path. The  [documentation](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html) does not make any special note about the AWS::Include Location property, but does say:

> To specify a local artifact in your template, specify a path to a local file or folder, as either an absolute or relative path. The relative path is a location that is relative to your template's location.

So, I would expect the AWS::Include to use the template's location, not the directory the command is executed from. In order to get the expected output, I either need to modify the path of the Location property to be from the directory the command is executed from or execute the command in the directory containing the template.yaml file.

### Example Configuration Files

```
# ./config/template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Description: Include test
Resources:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: ./include.yaml
  SampleFunction:
    Type: AWS::Serverless::Function
    FunctionName: Sample Function
    Properties:
      CodeUri: ./test.zip
```

```
# ./config/include.yaml
IncludedResource:
  Type: AWS::S3::Bucket
  Properties:
    BucketName: demobucket
```

### Command

`aws cloudformation package --template-file ./config/template.yaml --s3-bucket examplebucket`

### Expected Result

```
AWSTemplateFormatVersion: '2010-09-09'
Description: Include test
Resources:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: s3://examplebucket/include.yaml
  SampleFunction:
    FunctionName: Sample Function
    Properties:
      CodeUri: s3://examplebucket/test.zip
    Type: AWS::Serverless::Function
```

### Actual Result

```
AWSTemplateFormatVersion: '2010-09-09'
Description: Include test
Resources:
  Fn::Transform:
    Name: AWS::Include
    Parameters:
      Location: ./include.yaml
  SampleFunction:
    FunctionName: Sample Function
    Properties:
      CodeUri: s3://examplebucket/test.zip
    Type: AWS::Serverless::Function
```
