### ISSUE TITLE
AWS cloudformation deploy does not support newer nor customer provided runtimes

### ISSUE THREAD

**Issue by yunspace** [aws/aws-cli#3789]
I'm using `aws cloudformation deploy` with version 1.16.72 to deploy a SAM template with runtime `Provided`:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Custom Runtime

Resources:
  HelloWorld:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Custom Runtime 
      Runtime: Provided
      CodeUri: .
      Handler: custom
      MemorySize: 512
      Timeout: 10
      Policies: 
        - AWSLambdaRole
```

and I get the following error in CloudFormation console:

```
Value Provided at 'runtime' failed to satisfy constraint: Member must satisfy enum value set: [java8, 
nodejs6.10, nodejs8.10, python2.7, python3.6, dotnetcore1.0, dotnetcore2.0, dotnetcore2.1, go1.x] or be a 
valid ARN (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 9be2f808-fb62-11e8-8b75-23307281e7e6)
```

It seems also none of the newer runtimes such as Ruby are in the list, compared to `aws lambda create-function` command: https://docs.aws.amazon.com/cli/latest/reference/lambda/create-function.html

I don't think this is a AWS SAM issue since `sam deploy` is an alias to `aws cloudformation deploy`: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-deploy.html

Please advise if there are any workarounds or do we have to resort to `aws lambda create-function` for now.
