### ISSUE TITLE
aws cloudformation package fails with nested stack: "TemplateURL must be an Amazon S3 URL."

### ISSUE THREAD

**Issue by sharmmoh1983** [aws/aws-cli#3913]
I am getting following error when running master stack 
```
referenced by TemplateURL parameter of TemplateStack resource.
TemplateURL parameter of TemplateStack resource is invalid. It must be a S3 URL or path to CloudFormation template file.
```
```
TemplateStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: '/Users/test/appSync-test-resolvers-stack.yml'
 

```
What is the right way to provide local path in case of nested stack
