### ISSUE TITLE
Deleting CloudFormation stack with VPC does not remove DHCP options set

### ISSUE THREAD

**Issue by httpdigest** [aws/aws-cli#4076]
aws --version: `aws-cli/1.16.140 Python/3.6.7 Linux/4.18.0-17-generic botocore/1.12.130`

When using the following CloudFormation template:
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: "10.0.0.0/16"
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: "default"
  SubNetA:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: "10.0.0.0/24"
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  PublicSubNetARouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubNetA
  InternetGateway:
    Type: AWS::EC2::InternetGateway
  InternetGatewayRoute:
    Type: AWS::EC2::Route
    Properties:
      DestinationCidrBlock: "0.0.0.0/0"
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable
  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
```
The explicitly named resources are being created along with implicit resources created by default when creating a VPC, such as a default routing table and a DHCP options set.
However, when deleting the stack, the DHCP options group remains, whereas the routing table is successfully deleted. That means, when having a completely blank AWS Account and using create-stack with this template followed by delete-stack, one DHCP options set remains. If this process is repeated n times, then we will have n DHCP options sets.

Why is the DHCP options set not deleted along with all other implicitly created resources when the VPC is deleted again?
