### ISSUE TITLE
eks update-config - generates incorrect kube-config - missing aws-iam-authenticator command

### ISSUE THREAD

**Issue by javapapo** [aws/aws-cli#4145]
Version: aws-cli/1.16.156 Python/2.7.5 Linux/3.10.0-957.12.1.el7.x86_64 botocore/1.12.146
kubectl : 1.12.7
iam-aws-authenticator: 1.12.7

```bash
aws --region eu-west-1 eks update-kubeconfig --name XXXXXX
```

it generates 

```
 apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - eks
      - get-token
      - --cluster-name
      -  XXXXXX
      command: aws ---> it should be aws-iam-authenticator
```

Obviously whatever the attempt with the get-token - it should not break the previous mode
or give me the choice
```
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - xxxxx
      command: aws-iam-authenticator
```
The above makes kubectl invoke the aws cli but results to

```
You must specify a region. You can also configure your region by running "aws configure".
```

**Comment by joguSD** [comment]
Using `aws` instead of `aws-iam-authenticator` is intentional, but authentication failing is definitely not intentional. We pushed some changes in the last release to reduce the number of dependencies required (you should only need the `aws` command). Looking into this now.

**Comment by javapapo** [comment]
I understand I think I spotted a related P.R . Kubectl is invoking the aws cli but it fails ..

```
You must specify a region. You can also configure your region by running "aws configure".
```

**Comment by joguSD** [comment]
Interesting, does this always happen? Or is it intermittent?

**Comment by javapapo** [comment]
Always - it makes sense, since the new config instead of `aws-iam-authenticator` - changes the command to `aws` - then the cli is invoked. 

Either the `aws xxx` command that you expect to be executed is not , or there something with kubectl and this ? 

I am using the latest `kubectl` as fetched from the documents 1.12.7

**Comment by javapapo** [comment]
Also a side note - if and when this command makes it prime -the documentation needs to be updated: https://docs.aws.amazon.com/eks/latest/userguide/install-aws-iam-authenticator.html . Because now is still part of the official docs still. So this kind of change I have a feeling should be communicated with an EKS blog post?

**Comment by joguSD** [comment]
Does setting a region in either `~/.aws/config` or set the `AWS_REGION` env var make the command kubectl invoking work?

**Comment by javapapo** [comment]
hmm I need to test it - this and currently I have pivoted back to an older version of awscli that does not break this.

But still I don't think this is a safe assumption - because if you think so we do pass the region on the command : aws --region eu-west-1 

So whatever was the intention - the command is not properly templated on kubectl

**Comment by javapapo** [comment]
Maybe you can force this - when you generate the snippet? 

```
apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - eks
      - get-token
      - --region
     - <region>
      - --cluster-name
      -  XXXXXX
```

**Comment by sernst** [comment]
I'm encountering this issue as well. In my case the issue is intermittent. I can run a kubectl command multiple times in a row and get different errors/success outcomes. For example, running this command:

```
$ kubectl get roles --namespace kube-system

NAME                                             AGE
extension-apiserver-authentication-reader        14d
system::leader-locking-kube-controller-manager   14d
system::leader-locking-kube-scheduler            14d
system:controller:bootstrap-signer               14d
system:controller:cloud-provider                 14d
system:controller:token-cleaner                  14d
```

gives me the expected output. I can execute the same command again a moment later and get:

```
$ kubectl get roles --namespace kube-system

error: You must be logged in to the server (Unauthorized)
```

Occasionally, I'll get this error as well:

```
$ kubectl get roles --namespace kube-system

error: the server doesn't have a resource type "roles"
```

The profile I used to invoke the `eks update-kubeconfig` command does have a region name specified in the config file. Reverting the awscli worked for me as well to resolve the problem.

**Comment by jkpl** [comment]
I'm experiencing this problem as well. Some of the `kubectl` commands succeed, and some fail with `Unauthorized`. There doesn't seem to be clear pattern on which commands this happens on. Looking at the authenticator logs for EKS reveals that there are "access denied" errors with the message `input token was not properly formatted: illegal base64 data at input byte 1071`.

The old configs using aws-iam-authenticator seem to work still just fine, so that can still be used as a workaround.

**Comment by micahhausler** [comment]
@jkpl The illegal format error should be fixed in #4146 and will be rolled out shortly

**Comment by landaumd** [comment]
Hi all, my team is still running in to this issue. Is the fix to revert back to an older version of aws-cli?

**Comment by kyleknap** [comment]
@landaumd what version of the AWS CLI are you using? You can determine the version from running `aws --version`. In order to see the fix, you need to be using version `1.16.158`.

**Comment by javapapo** [comment]
I can confirm that the latest version , currently for me is `1.16.159` generates this config

```yaml
- name: arn:aws:eks:eu-west-1:486389912938:cluster/PRD1741-iccp-dev-eks-cluster-1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - eu-west-1
      - eks
      - get-token
      - --cluster-name
      - cluster1
      command: aws
      env:
      - name: AWS_PROFILE
        value: XXXXXX
```
