### ISSUE TITLE
Import AWS Step Functions state machine definition from external file

### ISSUE THREAD

**Issue by alexcasalboni** [aws/aws-cli#4335]
Officially, `AWS::StepFunctions::StateMachine` only allows a string definition as follows:

```yaml
MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties: 
        DefinitionString: "..."
        RoleArn: "..."
        StateMachineName: "..."
```

but it'd be great to be able to import/include/package the state machine definition from an external JSON file.

Something like this:

```yaml
MyStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties: 
        Definition: "definition.json"
        RoleArn: "..."
        StateMachineName: "..."
```

and then `aws cloudformation package` could take care of it.

I don't think if this would be easier/better to implement in the AWS SAM CLI since the `sam pacakge` command is just an alias of `aws cloudformation package`.

Any thoughts? Ping @heitorlessa
