### ISSUE TITLE
cloudformation package for LayerVersion misnamed

### ISSUE THREAD

**Issue by Dishwasha** [aws/aws-cli#4412]
When using cloudformation package for lambda layers, the generated zipfile name is incorrect and becomes the md5 hash value with no file extension.

This should have the same behavior as lambda functions,  where the zipfile is named after the last directory in the path specified in CodeUri and the extension .zip is appended.  Lambda layers should be named likewise using the ContentUri value.

```
...
Resources:
  TestLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: TestLayer
      ContentUri: ./layers/TestLayer
...
```

Running `aws cloudformation package --template test-layer.yml --s3-bucket mybucket --s3-prefix layer-directory --output json` will upload `s3://mybucket/layer-directory/aaa99f15bfe8cafb76a3bfe70eed290c` instead of `s3://mybucket/layer-directory/TestLayer.zip`
