### ISSUE TITLE
Bug in v2: "aws cloudformation package" result in "YAML not well-formed"

### ISSUE THREAD

**Issue by matsev** [aws/aws-cli#4955]
`aws cloudformation package` produces "not well-formed yaml" for `Fn::Join` together with `Fn::FindInMap` (when using serverless transform)

### Step by step

Given the following template:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Mappings:
  AccountMap:
    dev:
      AccountId: '112233445566'
    prod:
      AccountId: '1111222233333'

Parameters:
  Environment:
    Type: String
    Description: The environment name
    AllowedValues:
      - test
      - prod

Resources:
  MyLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: ./my-lambda
      Handler: index.handler
      Policies:
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - sts:AssumeRole
              Resource:
                - !Join ['', ['arn:aws:iam::', !FindInMap [AccountMap, test, AccountId], ':role/InvokeLambdaRole']]
                - !Join ['', ['arn:aws:iam::', !FindInMap [AccountMap, prod, AccountId], ':role/InvokeLambdaRole']]
```

Execute 

```bash
$ aws cloudformation package --template-file test.yaml --s3-bucket [bucket name] > test-out.yaml
```

Attempt to deploy:
```
$  aws cloudformation deploy --template-file test-out.yaml --stack-name test
```

### Expected result
The stack should be deployed successfully

### Actual result
> An error occurred (ValidationError) when calling the CreateChangeSet operation: Template format error: YAML not well-formed. (line 36, column 35)

----

The error is because the `Fn::Join` together with `Fn::FindInMap` is incorrect:

```yaml
Resources:
  MyLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs12.x
      CodeUri: s3://[bucket name]/[hash]
      Handler: index.handler
      Policies:
      - Version: 2012-10-17
        Statement:
        - Effect: Allow
          Action:
          - sts:AssumeRole
          Resource:
          - Fn::Join:
            - ''
            - ['arn:aws:iam::', Fn::FindInMap: [AccountMap, test, AccountId], :role/InvokeLambdaRole]
          - Fn::Join:
            - ''
            - ['arn:aws:iam::', Fn::FindInMap: [AccountMap, prod, AccountId], :role/InvokeLambdaRole]
```

----
```bash
$ aws --version
aws-cli/2.0.0 Python/3.7.4 Darwin/19.3.0 botocore/2.0.0dev4

```
