### ISSUE TITLE
unable to authenticate to EKS cluster via kubectl command using aws/iam authenticator 

### ISSUE THREAD

**Issue by rajivreddy** [aws/aws-cli#5075]
AWS cli version
```
$ aws --version
aws-cli/1.18.25 Python/3.7.2 Darwin/19.4.0 botocore/1.15.25
````
after setting up eks clister did ran this command to update my `.kube/config` file
```
aws --region us-west-2 eks get-token --cluster-name example  --profile internal
```
k8s config looks like below
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxxxx
    server: https://xxxxxxx.sk1.us-west-2.eks.amazonaws.com
  name: arn:aws:eks:us-west-2:123456789012:cluster/example
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:123456789012:cluster/example
    user: arn:aws:eks:us-west-2:123456789012:cluster/example
  name: arn:aws:eks:us-west-2:123456789012:cluster/example
current-context: arn:aws:eks:us-west-2:123456789012:cluster/example
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:123456789012:cluster/example
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-west-2
      - eks
      - get-token
      - --cluster-name
      - example
      command: aws
      env:
      - name: AWS_PROFILE
        value: internal
```
The expected behavior is I should be able to connect to the cluster and able to access my EKS cluster 
```
kubectl cluster-info
```
but I am getting 
```
error: You must be logged in to the server (Unauthorized)
```
User which is used for internal AWS profile has admin privileges.

We tried with aws cli to get token test via postman no luck.
```
aws --region us-west-2 eks get-token --cluster-name example  --profile internal
```
