### ISSUE TITLE
aws cloudformation package only permits s3.amazonaws.com (at us-east-1)

### ISSUE THREAD

**Issue by eijikominami** [aws/aws-cli#5092]
## Description

 I think `aws cloudformation package` command only permits strings  beginning with 's3://' or '**https://s3.amazonaws.com/BUCKET_NAME/**' and only S3 template url at `us-east-1` is succeed. S3 Bucket at other regions has a ''**http://s3-REGION_NAME.amazonaws.com/BUCKET_NAME/** domain, and the command understands it as a local file path. 

https://docs.aws.amazon.com/ja_jp/AWSCloudFormation/latest/UserGuide/aws-properties-stack.html
https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-application.html

## Steps to reproduce
Run `aws cloudformation package` with the following example template:

```
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A test CFN template

Resources:
  ExampleNestedStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://s3-ap-northeast-1.amazonaws.com/examplebucket/exampletemplate.yml
```

## Observed results
The following error occurs and `aws cloudformation package` command is failed.

```
Unable to upload artifact https://s3-ap-northeast-1.amazonaws.com/examplebucket/exampletemplate.yml referenced by TemplateURL parameter of ExampleNestedStack resource.
TemplateURL parameter of ExampleNestedStack resource is invalid. It must be a S3 URL or path to CloudFormation template file. Actual: /Users/eiji/Documents/VisualStudioCode/test2/https:/s3-ap-northeast-1.amazonaws.com/examplebucket/exampletemplate.yml
```

If TemplateURL is rewritten to a string starting with '**https://s3.amazonaws.com/**', it succeeds.
