### ISSUE TITLE
ECR deployment auth issues from Docker 

### ISSUE THREAD

**Issue by aradwyr** [aws/aws-cli#5163]
None of the solutions from https://github.com/aws/aws-cli/issues/2875 are working for me, so far I've tried various iterations of the `aws ecr get-login-password` command in a Docker image. 

For ex: 
```
 aws ecr get-login-password --region us-west-2 | docker login --password-stdin --username AWS "$(aws sts get-caller-identity --query Account --output text).dkr.ecr.us-west-2.amazonaws.com"
```
Results in: 
```
Unable to locate credentials. You can configure credentials by running "aws configure".
Error: Cannot perform an interactive login from a non TTY device
```
----------
Vast majority of the time I'm encountering this error: `no basic auth credentials` but I'm only facing this error once I'm at the last step trying to push the image: 

`bitbucket-pipelines.yml` file: 
```
image: node:8-alpine

pipelines:
  default:
    - step:
        name: Build and push ECR image
        services:
          - docker
        script:
          - npm install
          - docker pull amazon/aws-cli:latest
          - alias aws='docker run --rm amazon/aws-cli'
          - eval $(aws ecr get-login-password --region us-west-2 | docker login --password-stdin --username AWS "$(aws sts get-caller-identity --query Account --output text).dkr.ecr.us-west-2.amazonaws.com")
          - docker build -t $IMAGE_NAME .
          - docker tag <ecr_repo>:<tag> <image_uri>
          - docker push <image_uri>
```

I've even included `aws configure` in the process above but still the `no basic auth credentials` error remains:
```
           - aws configure set aws_access_key_id "${AWS_ACCESS_KEY_ID}"
           - aws configure set aws_secret_access_key "${AWS_SECRET_ACCESS_KEY}"
````

Version: 
 ```
aws --version
aws-cli/2.0.10 Python/3.7.3 Linux/4.19.95-flatcar botocore/2.0.0dev14
```
