### ISSUE TITLE
aws eks token with longer expiry time

### ISSUE THREAD

**Issue by sfc-gh-pkrishnamurthy** [aws/aws-cli#5185]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [ x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x ] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
I use aws eks get-token in a kube-config file to authenticate with EKS. The token's presigned url (https://github.com/aws/aws-cli/blob/develop/awscli/customizations/eks/get_token.py#L30) timeout causes my job to get 401s when performing any operation against the K8s api-server beyond 1 hr. 
I periodically refresh the token by reloading the kube_conf file but that does not seem to help. 

Is there a way to get a token with a longer presigned url timeout?

**SDK version number**
1.18.49
**Platform/OS/Hardware/Device**
What are you running the cli on?
centos 7
**To Reproduce (observed behavior)**
Steps to reproduce the behavior
use
```
user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--cluster-name"
        - "k8s-1"
        - "--region"
        - "us-west-2"
``` 
in kube-conf have a client load the kube_config and a sample script like below

```
import time
from kubernetes import client as kubernetesClient
from kubernetes import config as kubernetesConfig
from kubernetes.client.rest import ApiException

kubernetesConfig.load_kube_config(config_file=<path/to/kubeConfFile>)
kubeClient = kubernetesClient.CoreV1Api()
namespace = kube-system

while i < 61:
     try:
          api_response = kubeClient.list_namespaced_pod(namespace)
     except ApiException as e:
          if e.status == 401:
               print("This is the failure in question")
          raise e
     time.sleep(60)
```

When the script is executed one would observe that you get 401 errors after the 1 hour mark

expected result: More of a question on how to get a token with a longer expiry ?

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

**Additional context**
