### ISSUE TITLE
`aws cloudformation package` does bad things with all-digit strings with a leading `0` (yaml)

### ISSUE THREAD

**Issue by stilvoid** [aws/aws-cli#5363]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
Taking the following template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Account:
    Default: 012345678901
    Type: String

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "bucket-${Account}"
```

and running `aws cloudformation package --template-file in.template --output-template out.template --s3-bucket <a-bucket>`, I see the following output in `out.template`

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  Account:
    Default: 12345678901
    Type: String
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: bucket-${Account}
```

You can see the default value of the `Account` parameter is incorrect. This is annoyingly frequent bug in anything that parses YAML. As of YAML 1.2, such values should always be interpreted as strings but many parsers aren't up to date or just plain get it wrong.

**SDK version number**

botocore/2.0.0dev30

**Platform/OS/Hardware/Device**
What are you running the cli on?

Linux/5.7.4-arch1-1

**To Reproduce (observed behavior)**
Steps to reproduce the behavior

See above :)

**Expected behavior**

*Any* value that is comprised entirely of digits and has a leading zero should be treated as a string

**Logs/output**
Get full traceback and error logs by adding `--debug` to the command.

N/A

**Additional context**

Reported in https://github.com/aws-cloudformation/rain/issues/27
