### ISSUE TITLE
Include SessionManagerPlugin in Docker image

### ISSUE THREAD

**Issue by utterlyforked** [aws/aws-cli#5373]
The provided Amazon/aws-cli docker image is a great solution for deploying the AWS-CLI easily. I don't need to install the CLI or dependencies on my local machine. It does not however support the use of AWS SSM because the SessionManagerPlugin is not installed in the image.

Please include the AWS SSM Plugin in the image.

**Comment by kdaily** [comment]
Thanks for the feature request, @utterlyforked!

**Comment by aries1980** [comment]
How can we help to get the one-liner change into the image?

**Comment by andymac4182** [comment]
This would be amazing if it could get fixed up. This removes the docker image as an option for us :(

**Comment by horttanainen** [comment]
Dear AWS have you given up on this project?

**Comment by aries1980** [comment]
If someone could explain us why this is a hard thing to add give the solution above, that would hush away the thoughts on this project has a bad governance.

**Comment by alimeerutech** [comment]
+1

**Comment by dieterrosch** [comment]
How can this one line change be open for 2 years already?

**Comment by realsby** [comment]
+1

**Comment by kevkearney** [comment]
+1

**Comment by alexinfoblox** [comment]
+100500

**Comment by mshytikov** [comment]
+1

**Comment by NikDevPHP** [comment]
+1

**Comment by lorengordon** [comment]
Maybe tag the image separately, similar to how many projects publish images with tag modifiers like "full" "slim" "buster" "debian" etc...

**Comment by Disruption** [comment]
In case it's useful for anyone, we were using this in github actions, so I created a very small repository to customize the action. Since it's public, feel free to use it if anyone is on the same situation, like:
```
name: Whatever task you want to perform requiring the session manager plugin
uses: KadooRegalos/AwsCliSMP@master
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
with:
  args: your aws cli command, like ecs execute-command to perform database migrations on a running task
```
So basically, the only change is on the "uses" line, where instead of the official aws cli docker image, we have our repo action "KadooRegalos/AwsCliSMP@master"
