### ISSUE TITLE
Allow cloudformation deploy to accept a paramater file in YAML format

### ISSUE THREAD

**Issue by bs-thomas** [aws/aws-cli#5473]
**Is your feature request related to a problem? Please describe.**
Yes, in aws cloudformation deploy, we now support JSON file as the format for --parameter-overrides.  This is really good news, because the long unresolved problem (with Windows especially) with specifying multi-line parameters is now finally resolved by supporting a JSON formatted file.

via this issue: Allow cloudformation deploy to accept a paramater file #2828  (https://github.com/aws/aws-cli/issues/2828)

However, the values look really ugly.  Like this:  `"first line\nsecond line\nthird line"`  Ew, yuck!

**Describe the solution you'd like**
Maybe supporting YAML formatted file will resolve this.

**Describe alternatives you've considered**
Could be other well-known common formats too, but YAML seems to be the most popular.

**Additional context**

Something like this?

```
Parameters:
  DesiredCount: 2
  MaxCapacity: 3
  MinCapacity: 2
  MaximumPercent: 150
  MinimumHealthyPercent: 49
  MultiLineStuff: |
    first line
    second line
    third line
```

Thank you very much for the time going through this.
