### ISSUE TITLE
EKS command yields single word error when config is not parsable

### ISSUE THREAD

**Issue by hlascelles** [aws/aws-cli#5532]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  

**The bug**
When the `~/.kube/config` file is unparsable, `aws eks` returns unhelpful errors:

```
aws eks update-kubeconfig --name foo

'name'
```

The above is the entire output, just the word "name", with exit code 255.

**SDK version number**
```
❯ aws --version
aws-cli/2.0.46 Python/3.8.5 Linux/5.4.0-42-generic source/x86_64.linuxmint.20
```

**Platform/OS/Hardware/Device**
Mint Linux

**To Reproduce (observed behavior)**
1) Have a corrupt `~/.kube/config`
2) Attempt to update it.

My config file was of the form:

```
❯ cat ~/.kube/config                                                         
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: THECERTBASE64
    server: https://SOMETHING.sk1.eu-west-1.eks.amazonaws.com
  name: arn:aws:eks:eu-west-1:1234567890:cluster/foo
- cluster:
    certificate-authority-data:% 
```

**Expected behavior**
A better error should indicate the config file is a problem.

**Additional context**
I do not know how the cluster config became corrupted, it has never been edited manually.

To fix the issue, just move the config file and allow it to be recreated by trying again: `mv ~/.kube/config ~/.kube/config.bak`
