### ISSUE TITLE
AWS::Synthetics::Canary Package support for code

### ISSUE THREAD

**Issue by jk2l** [aws/aws-cli#5753]
**Is your feature request related to a problem? Please describe.**
I would like to be able to package code from my local directory similar to AWS::Lambda::Function's Code block

**Describe the solution you'd like**
```
  TestFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: lambda/
    
  Heartbeat:
    Type: AWS::Synthetics::Canary
    Properties:
      Code: lambda/
```
Similar to `AWS::Lambda::Function` in which `aws cloudformation package` can change `Code` block into a file reference in S3. Extend this functionality to `AWS::Synthetics::Canary` Code block

**Describe alternatives you've considered**
CI/CD tool that manually package the file into zip. make a random hash and upload to S3

**Additional context**
All supported package reference can be found here https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html
