### ISSUE TITLE
"aws eks update-kubeconfig" runs into "YamlError while loading kubeconfig: while scanning a simple key"

### ISSUE THREAD

**Issue by Mierpo** [aws/aws-cli#5854]
I'm trying to setup AWS commandline tool to access an eks cluster from a local ubuntu installation. The following command runs into an error:

```
$ aws eks update-kubeconfig --name "[REDACTED]" --region=[REDACTED]

YamlError while loading kubeconfig: while scanning a simple key
  in "/home/[REDACTED]/.kube/config", line 30, column 1
could not find expected ':'
  in "/home/[REDACTED]/.kube/config", line 32, column 1
```

The following command also runs into the same issue:

```
$ kubectl get all

error: error loading config file "/home/[REDACTED]/.kube/config": yaml: line 32: could not find expected ':'
```

Version information:

```
$ aws --version

aws-cli/2.1.16 Python/3.7.3 Linux/4.4.0-19041-Microsoft exe/x86_64.ubuntu.20 prompt/off

$ kubectl version --client

Client Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:21:03Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

KubeConfig (redacted contents):

```
kubectl_config = apiVersion: v1
preferences: {}
kind: Config

clusters:
- cluster:
    server: [REDACTED]
    certificate-authority-data: [REDACTED]
  name: [REDACTED]

contexts:
- context:
    cluster: [REDACTED]
    user: [REDACTED]
  name: [REDACTED]

current-context: [REDACTED]

users:
- name: [REDACTED]
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "[REDACTED]"

region = [REDACTED]
```

The problem does not occur on my windows machine with the following versions:

```
$ aws --version

aws-cli/2.0.26 Python/3.7.7 Windows/10 botocore/2.0.0dev30

$ kubectl version --client

Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"windows/amd64"}
```

However, the contents of the kubeconfig file is also entirely different (much more content) with the version I have on windows:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: [REDACTED]
    server: [REDACTED]
  name: [REDACTED]
- cluster:
    certificate-authority-data: [REDACTED]
    server: [REDACTED]
  name: [REDACTED]
contexts:
- context:
    cluster: [REDACTED]
    user: [REDACTED]
  name: [REDACTED]
- context:
    cluster: [REDACTED]
    user: [REDACTED]
  name: [REDACTED]
current-context: [REDACTED]
kind: Config
preferences: {}
users:
- name: [REDACTED]
  user:
    client-certificate-data: [REDACTED]
    client-key-data: [REDACTED]
- name: [REDACTED]
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - [REDACTED]
      - eks
      - get-token
      - --cluster-name
      - [REDACTED]
      command: aws
```

**Expected behaviour**

The aws eks update-kubeconfig command should work  the same for different versions and different operating systems.

**Actual behaviour**
aws eks update-kubeconfig produces an invalid kube config file on ubuntu, aws version aws-cli/2.1.16

**Work-around**

Copy the config file created in windows to ubuntu.
