### ISSUE TITLE
AWS CLI Docker shows failed for aws cli command without any proper debug message

### ISSUE THREAD

**Issue by tan31989** [aws/aws-cli#5902]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone though the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution
  
**Describe the bug**
When we use the latest dockerhub image for `docker pull amazon/aws-cli`, i.e. the latest at this point being: `docker pull amazon/aws-cli:2.1.21`, we get a message like

`sh: line 1: 6 Killed aws s3 sync s3://bucket/prefix/ . --debug`

---
**SDK version number**

**Platform/OS/Hardware/Device**
Running a docker

**To Reproduce (observed behavior)**
Pull the docker version 2.1.21 and run the command `s3 sync s3://bucket/prefix/ . --debug`

**Expected behavior**
Should successfully sync the folder

---
**Logs/output**
Even after adding `--debug`, I see just the following error:

`sh: line 1: 6 Killed aws s3 sync s3://bucket/prefix/ . --debug`

---

**Additional context**
*After reverting the docker version to 1.2.0, it started working properly*

**Comment by kdaily** [comment]
Hi @tan31989,

I tested on Mac OSX with the following Docker version:

```
❯ docker --version
Docker version 20.10.2, build 2291f61
```

When I run an `s3 sync` I see debug logs and the command completes successfully. In order to debug further, you might need to override the entrypoint and run the command from there. This is what I do to perform that:

```
docker run --entrypoint /bin/bash -v ~/.aws:/root/.aws --rm -it amazon/aws-cli:2.1.21
```

**Comment by tan31989** [comment]
Hi @kdaily,

Thanks for updating on this.
For me as well locally there was no issue.

We execute this as a sidecar in one of our internal application using helm deployment configuration. 
The Container also uses an IAM Role to connect to S3. The older version was working seamlessly and now somehow the same doesn't work and is not even printing the debug logs.

Here is the helm deployment configuration:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 5
  labels:
    app: docs-qa-app
    chart: docs-0.1.0
    heritage: Tiller
    release: docs-qa
  name: qa-docs
  namespace: dm-qa
  selfLink: /apis/apps/v1/namespaces/dm-qa/deployments/qa-docs
  uid: 9a765434-3df5-4941-b8bf-f401d8e401e7
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        iam.amazonaws.com/role: arn:aws:iam::<iam-role>
      labels:
        app: docs-qa-app
        release: docs-qa
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: squidfunk/mkdocs-material:latest
        imagePullPolicy: Always
        name: docs
        ports:
        - containerPort: 8000
          protocol: TCP
        volumeMounts:
        - mountPath: /docs
          name: docs
      - command:
        - sh
        - -c
        - echo $PWD; while true; do aws s3 sync s3://my-company-docs/qa/ . --delete ; sleep
          3600; done;
        image: amazon/aws-cli:2.1.0
        imagePullPolicy: Always
        name: refresh-docs
        volumeMounts:
        - mountPath: /docs
          name: docs
        workingDir: /docs
      initContainers:
      - command:
        - sh
        - -c
        - echo $PWD; aws s3 sync s3://docs/qa/ . --debug
        image: amazon/aws-cli:2.1.0
        imagePullPolicy: Always
        name: clone-docs
        volumeMounts:
        - mountPath: /docs
          name: docs
        workingDir: /docs
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: docs
```

This is the part which had to be changed to point to an older version:

```yaml
      initContainers:
      - command:
        - sh
        - -c
        - echo $PWD; aws s3 sync s3://docs/qa/ . --debug
        image: amazon/aws-cli:2.1.0    # amazon/aws-cli changed to amazon/aws-cli:2.1.0
```
