### ISSUE TITLE
aws eks get-token support external-id

### ISSUE THREAD

**Issue by vikas027** [aws/aws-cli#5942]
**Is your feature request related to a problem? Please describe.**
There is no way to refer to an external ID while assuming a role with aws cli v2.

**Describe the solution you'd like**
I should be able to define the external ID like this

```yaml
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - --region
        - ap-southeast-2
        - eks
        - get-token
        - --cluster-name
        - myeks
        - --role-arn
        - <arn>
        - --external-id
        - 11111111
 ```

**Describe alternatives you've considered**
Disable external ID in the IAM role trust relationship policy
