### ISSUE TITLE
Overriding default instance type for beanstalk environment is not working

### ISSUE THREAD

**Issue by puneetpandey** [aws/aws-cli#6013]
I have a cloudformation template and I would like to choose instance type dynamically for each environment. Here's what I am trying to do:

````
AWSTemplateFormatVersion: 2010-09-09
Description: MyApp CloudFormation
Conditions:
  ProductionCondition: !Equals [!Ref 'AWS::StackName', production]
  NotProductionCondition: !Not [!Equals [!Ref 'AWS::StackName', production]]
Parameters:
  RailsApplicationTemplate:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: t2.micro
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: AWS_ENV
        Value: web
  RailsWebEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    DependsOn:
      - RailsApplicationTemplate
    Properties:
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: !If [ProductionCondition, 't2.large', 't2.medium']
  RailsWorkerEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    DependsOn:
      - RailsApplicationTemplate
    Properties:
      OptionSettings:
      - Namespace: aws:autoscaling:launchconfiguration
        OptionName: InstanceType
        Value: t2.medium
      - Namespace: aws:elasticbeanstalk:application:environment
        OptionName: AWS_ENV
        Value: worker
````

Whenever I run ` aws cloudformation update-stack --stack-name staging --template-body file://cloudformation/template.yml --capabilities CAPABILITY_IAM` the CF command does not change the `InstanceType` and always use `t2.micro` as its value. On the other side, it does change the default value of `AWS_ENV` to `Worker` for Worker environment.

Other solutions I have tried are:
1. By removing `InstanceType` from `RailsApplicationTemplate` and use it individually for each environment. - But that didn't work.

Is this supported? Am I doing something wrong here?
Please advise.
