### ISSUE TITLE
Problem identifying LaunchTemplate MetadataOptions InstanceMetadataTags

### ISSUE THREAD

**Issue by ctaslimsq** [aws/aws-cli#6729]
Confirm by changing [ ] to [x] below to ensure that it's a bug:
- [x] I've gone through the [User Guide](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-welcome.html) and the [API reference](https://docs.aws.amazon.com/cli/latest/reference/)
- [x] I've searched for [previous similar issues](https://github.com/aws/aws-cli/issues) and didn't find any solution

**Describe the bug**
When running `ec2 create-launch-template-version` command, the new feature (https://aws.amazon.com/about-aws/whats-new/2022/01/instance-tags-amazon-ec2-instance-metadata-service/) failed the dry run.
```
Parameter validation failed:
Unknown parameter in LaunchTemplateData.MetadataOptions: "InstanceMetadataTags", must be one of: HttpTokens, HttpPutResponseHopLimit, HttpEndpoint, HttpProtocolIpv6
```

Filed a similar ticket in the cfn-lint repo https://github.com/aws-cloudformation/cfn-lint/issues/2215

snippet of cloudformation content

```
Resources:
  ComputeRegressionTestLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName:
        - 'SomeName'
      LaunchTemplateData:
        InstanceType: m5.xlarge
        KeyName: kochiku
        MetadataOptions:
          HttpTokens: required
          HttpPutResponseHopLimit: 2
          InstanceMetadataTags: enabled  
```

official documentation: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-launchtemplate-launchtemplatedata-metadataoptions.html

**SDK version number**
```
$ aws --version
aws-cli/2.4.14 Python/3.8.8 Linux/3.10.0-1127.18.2.el7.x86_64 exe/x86_64.centos.7 prompt/off
```

**Platform/OS/Hardware/Device**
CentOS Linux 7 (Core)

**To Reproduce (observed behavior)**
Run `aws ec2 create-launch-template-version` command with content

```
Resources:
  SomeTemplateName:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        MetadataOptions:
          InstanceMetadataTags: enabled  
```

**Expected behavior**
to pass, but it's not working as it produces error 

**Logs/output**
```
Parameter validation failed:
Unknown parameter in LaunchTemplateData.MetadataOptions: "InstanceMetadataTags", must be one of: HttpTokens, HttpPutResponseHopLimit, HttpEndpoint, HttpProtocolIpv6
Dry run did not pass with exit code 252...exiting

```

**Additional context**
