### ISSUE TITLE
cloudformation deploy references incorrect format for CodePipeline style parameters

### ISSUE THREAD

**Issue by corey-cole** [aws/aws-cli#6907]
### Describe the bug

The documentation for the cloudformation deploy subcommand references invalid JSON when describing the CodePipeline style overrides.  At present, the docs reference this JSON construct:

```json
[
    "Parameters": {
        "Key1": "Value1",
        "Key2": "Value2"
    }
]
```
This is not valid JSON, as the root element is an array.
The correct construct for this (validated with a minimal log group template) is:
```json
{
    "Parameters": {
        "Key1": "Value1",
        "Key2": "Value2"
    }
}
```

### Expected Behavior

I expected that following the provided documentation would result in a CloudFormation stack being deployed.

### Current Behavior

Passing parameters as described in the docs results in an immediate error

### Reproduction Steps

Template:
```yaml
AWSTemplateFormatVersion: "2010-09-09"

Description: Simple template

Parameters:
  pGroupName:
    Type: String

Resources:
  rLogGroup:
    Type:  AWS::Logs::LogGroup
    Properties:
        LogGroupName: !Ref pGroupName
```

Parameters (per docs):
```json
[
    "Parameters": {
        "pGroupName": "InnocuousLogGroup"
    }
]
```

Results:
```unix
aws cloudformation deploy --stack-name cp-format-validation --template-file mintemplate.yaml --parameter-overrides file://parameters-fixed.json

Expecting property name enclosed in double quotes: line 4 column 5 (char 69)
```

### CLI version used

aws-cli/2.6.0 Python/3.9.12 Darwin/20.6.0 source/arm64 prompt/off

### Environment details (OS name and version, etc.)

macOS 11.6.5
