### ISSUE TITLE
String starting with 0 ("0xx..") is taken as integer with "aws cloudformation package" command

### ISSUE THREAD

**Issue by AnuragChandra10** [aws/aws-cli#6908]
### Describe the bug

While creating a package using `aws cloudformation package` command and then using the `aws cloudformation create-stack` command using to create the packaged template leads to take a string parameter starting with "0" as string. This happens only with `aws-cli/1.23.1` (likely with aws-cli 1.x versions as `aws-cli/1.23.1` is a fairly new version at present).

### Expected Behavior

The parameter stored should be the account ID as it is: 012345678901

### Current Behavior

The string is being stored as a number with scientific notation.

### Reproduction Steps

Use a Template with parameter starting with "0":

```
Mappings: 
  GovAccountMapping: 
    dev: 
      AccountId: "012345678901"

Resources:
  BasicParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: "accountId"
      Type: String
      Value: !FindInMap [GovAccountMapping, dev , AccountId]
      Description: SSM Parameter for running date command.
```

Package command: `aws cloudformation package --template-file parameter.yaml --s3-bucket bucket-name --output-template-file packaged-template.yaml`

Stack creation: `aws cloudformation create-stack --stack-name myteststack --template-body file://packaged-template.yaml`

### Possible Solution

A workaround at present is to use the `--use-json` option to format the output template as json.

### CLI version used

aws-cli/1.23.1

### Environment details (OS name and version, etc.)

Mac OS
