### ISSUE TITLE
`Empty KUBERNETES_EXEC_INFO` warning when running `aws eks get-token`

### ISSUE THREAD

**Issue by timfallmk** [aws/aws-cli#6935]
### Describe the bug

This is likely related to https://github.com/kubernetes/kubectl/issues/1210

Using the newest update contained the in above patch, `kubectl` auth commands run as expected. However any requests to `aws eks get-token` that don't come from `kubectl` itself (or a tool using a similar mechanism) result in the following warning:
```shell
Empty KUBERNETES_EXEC_INFO, defaulting to client.authentication.k8s.io/v1alpha1. This is likely a bug in your Kubernetes client. Please update your Kubernetes client.
```
This might just need some documentation to prevent confusion, but I'm already seeing users run into it and ask. And the usual [reddit suspects](https://www.reddit.com/r/kubernetes/comments/um1wa1/what_is_kubernetes_exec_info_and_why_would_it_be/)

### Expected Behavior

- More detailed warning message? 
- Suppression of warnings when an interactive prompt is detected?
- Documentation notes?

### Current Behavior

`aws eks get-token` (with valid credentials)
Output:
```shell
Empty KUBERNETES_EXEC_INFO, defaulting to client.authentication.k8s.io/v1alpha1. This is likely a bug in your Kubernetes client. Please update your Kubernetes client.
<token>
```

### Reproduction Steps

`aws eks get-token`

### CLI version used

`aws-cli/2.6.3 Python/3.9.12 Darwin/21.4.0 source/arm64 prompt/off`

### Environment details (OS name and version, etc.)

macOS 12.3.1

**Comment by bassco** [comment]
To workaround this pin `awscli==1.23.8` in your deployment images due to the api-version change in [1.23.9](https://github.com/aws/aws-cli/blob/develop/CHANGELOG.rst#1239)

**Comment by teochenglim** [comment]
1. upgrade to kubectl 1.24, i use homebrew.

2a. in your ~/.kube/config, it is still using v1alpha1, replace it too.

```yaml
users:
- name: [redact]
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1 ### was client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - [redact]
      - eks
      - get-token
      - --cluster-name
      - [redact]
      command: aws
      env:
      - name: AWS_PROFILE
        value: [redact]
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

2b. Or delete your ~/.kube/config and use awscli to recreate again.

```shell
aws eks update-kubeconfig --name [cluster_name]
```
