### ISSUE TITLE
AWS CLI signal-resource operation does not signal CreationPolicy

### ISSUE THREAD

**Issue by istraka** [aws/aws-cli#7133]
### Describe the bug

When I define EC2 Instance with creation policy:
```
CreationPolicy:
            ResourceSignal:
                Timeout: PT3M
```
and send signal using aws cli
```
aws cloudformation signal-resource --stack-name ${AWS::StackName} --region ${AWS::Region} --logical-resource-id EC2Instance --status SUCCESS --unique-id 1234
```
the stack fails to receive signal and the create operation of instance fails. 

### Expected Behavior

I expect signal to be received and instance to be created successfully.

### Current Behavior

I get `Failed to receive 1 resource signal(s) within the specified duration`

### Reproduction Steps

Deploy the CloudFormation template:
```
AWSTemplateFormatVersion: "2010-09-09"
Metadata:
    Generator: "former2"
Description: ""
Resources:
    EC2KeyPair:
        Type: "AWS::EC2::KeyPair"
        Properties:
            KeyName: !Join ["-", ["key", !Ref AWS::StackId]]
            KeyType: "rsa"
    EC2VPC:
        Type: "AWS::EC2::VPC"
        Properties:
            CidrBlock: "172.31.0.0/16"
            EnableDnsSupport: true
            EnableDnsHostnames: true
            InstanceTenancy: "default"
    IAMRole:
        Type: "AWS::IAM::Role"
        Properties:
            Path: "/"
            RoleName: "SignalRole2"
            AssumeRolePolicyDocument: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ec2.amazonaws.com\"},\"Action\":\"sts:AssumeRole\"}]}"
            MaxSessionDuration: 3600
            ManagedPolicyArns:
                - "arn:aws:iam::aws:policy/AWSCloudFormationFullAccess"
            Description: "Allows EC2 instances to call AWS services on your behalf."

    IAMInstanceProfile:
        Type: "AWS::IAM::InstanceProfile"
        Properties:
            Path: "/"
            InstanceProfileName: !Ref IAMRole
            Roles:
                - !Ref IAMRole

    EC2SecurityGroup:
        Type: "AWS::EC2::SecurityGroup"
        Properties:
            GroupDescription: "Allows any connection"
            GroupName: "allow-any"
            VpcId: !Ref EC2VPC
            SecurityGroupIngress:
                -   CidrIp: "0.0.0.0/0"
                    IpProtocol: "-1"
                -   CidrIpv6: "::/0"
                    IpProtocol: "-1"
            SecurityGroupEgress:
                -   CidrIp: "0.0.0.0/0"
                    IpProtocol: "-1"

    EC2Instance:
        Type: "AWS::EC2::Instance"
        CreationPolicy:
            ResourceSignal:
                Timeout: PT3M
        DependsOn:
            - EC2KeyPair
        Properties:
            ImageId: "ami-0cff7528ff583bf9a"
            InstanceType: "t3.medium"
            KeyName: !Ref EC2KeyPair
            AvailabilityZone: !GetAtt EC2Subnet.AvailabilityZone
            Tenancy: "default"
            SubnetId: !Ref EC2Subnet
            EbsOptimized: false
            SecurityGroupIds:
                - !Ref EC2SecurityGroup
            SourceDestCheck: true
            IamInstanceProfile: !Ref IAMRole
            BlockDeviceMappings:
                -   DeviceName: "/dev/sda1"
                    Ebs:
                        Encrypted: false
                        VolumeSize: 10
                        VolumeType: "gp2"
                        DeleteOnTermination: true
            Tags:
                -   Key: "Name"
                    Value: "signalTest"
            HibernationOptions:
                Configured: false
            CpuOptions:
                CoreCount: 1
                ThreadsPerCore: 2
            EnclaveOptions:
                Enabled: false
            UserData:
                Fn::Base64:
                    !Sub |
                        #!/usr/bin/env bash
                        rm -rf aws

                        yum install -y unzip
                        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
                        unzip -q awscliv2.zip
                        chmod +x ./aws/dist/aws
                        alias aws=`pwd`/aws/dist/aws
                        aws cloudformation signal-resource --stack-name ${AWS::StackName} --region ${AWS::Region} --logical-resource-id EC2Instance --status SUCCESS --unique-id 1234

    EC2Instance2:
        Type: "AWS::EC2::Instance"
        CreationPolicy:
            ResourceSignal:
                Timeout: PT3M
        DependsOn:
            - EC2KeyPair
        Properties:
            ImageId: "ami-0cff7528ff583bf9a"
            InstanceType: "t3.medium"
            KeyName: !Ref EC2KeyPair
            AvailabilityZone: !GetAtt EC2Subnet.AvailabilityZone
            Tenancy: "default"
            SubnetId: !Ref EC2Subnet
            EbsOptimized: false
            SecurityGroupIds:
                - !Ref EC2SecurityGroup
            SourceDestCheck: true
            IamInstanceProfile: !Ref IAMRole
            BlockDeviceMappings:
                -   DeviceName: "/dev/sda1"
                    Ebs:
                        Encrypted: false
                        VolumeSize: 10
                        VolumeType: "gp2"
                        DeleteOnTermination: true
            Tags:
                -   Key: "Name"
                    Value: "signalTest2"
            HibernationOptions:
                Configured: false
            CpuOptions:
                CoreCount: 1
                ThreadsPerCore: 2
            EnclaveOptions:
                Enabled: false
            UserData:
                Fn::Base64:
                  !Sub |
                    #!/usr/bin/env bash
                    /opt/aws/bin/cfn-signal -e 0 --stack ${AWS::StackName} --region ${AWS::Region} --resource EC2Instance2

    EC2Subnet:
        Type: "AWS::EC2::Subnet"
        DependsOn:
            - EC2VPC
        Properties:
            AvailabilityZone: !Sub "${AWS::Region}a"
            CidrBlock: "172.31.0.0/20"
            VpcId: !Ref EC2VPC
            MapPublicIpOnLaunch: true

    EC2InternetGateway:
        Type: "AWS::EC2::InternetGateway"

    EC2Route:
        Type: "AWS::EC2::Route"
        DependsOn:
            - EC2Subnet
            - EC2InternetGateway
            - EC2RouteTable
        Properties:
            DestinationCidrBlock: "0.0.0.0/0"
            GatewayId: !Ref EC2InternetGateway
            RouteTableId: !Ref EC2RouteTable

    EC2VPCGatewayAttachment:
        Type: "AWS::EC2::VPCGatewayAttachment"
        Properties:
            InternetGatewayId: !Ref EC2InternetGateway
            VpcId: !Ref EC2VPC

    EC2RouteTable:
        Type: "AWS::EC2::RouteTable"
        Properties:
            VpcId: !Ref EC2VPC

    EC2SubnetRouteTableAssociation:
        DependsOn:
            - EC2Route
        Type: "AWS::EC2::SubnetRouteTableAssociation"
        Properties:
            RouteTableId: !Ref EC2RouteTable
            SubnetId: !Ref EC2Subnet
```

### CLI version used

aws-cli/2.7.18

### Environment details (OS name and version, etc.)

Amazon Linux release 2 (Karoo), 5.10.118-111.515.amzn2.x86_64
