### ISSUE TITLE
Lambda code does not get zipped during `package` command when using substacks

### ISSUE THREAD

**Issue by GasimGasimzada** [aws/aws-cli#7356]
### Describe the bug

I have a cloudformation template for creating a lambda function that uses a local JS file as the source code:

```yaml
# Filename: auth/auth.yml
# Lambda JS file: auth/lambda-pre-signup.js
Resources:
  ## Other resources here
  MyPreSignupLambda:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - arm64
      Code: 'lambda-pre-signup.js'
      Handler: 'lambda-pre-signup.handler'
      Runtime: nodejs16.x
      PackageType: Zip
      #Role: !GetAtt MyRole.Arn
```

I also have a root template that references the template above to create a substack:

```
# Filename: root.yml
Resources:
  MyAuth:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./auth/auth.yml
```

I run the `package` command to upload the resources to S3 and use them for deployment:

```bash
aws cloudformation package --template-file root.yml --s3-bucket my-bucket --generated-template-file generated-root.yml
```

The stack template (`MyAuth`) gets uploaded to S3 correctly and the source code resource it has also gets uploaded to S3. However, the uploaded source code is not a zipped file for some reason. As a result, when I try to deploy the root stack, I get an error about Lambda function cannot be zipped. 

### Expected Behavior

The source code in the substack is zipped before being uploaded

### Current Behavior

Source code in the substack is not zipped.

### Reproduction Steps

Substack: `auth/auth.yml`

```yaml
# Filename: auth/auth.yml
# Lambda JS file: auth/lambda-pre-signup.js
Resources:
  ## Other resources here
  MyPreSignupLambda:
    Type: AWS::Lambda::Function
    Properties:
      Architectures:
        - arm64
      Code: 'lambda-pre-signup.js'
      Handler: 'lambda-pre-signup.handler'
      Runtime: nodejs16.x
      PackageType: Zip
      #Role: !GetAtt MyRole.Arn
```

Root stack: `root.yml`

```
# Filename: root.yml
Resources:
  MyAuth:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: ./auth/auth.yml
```

Run the package command with a bucket: `aws cloudformation package --template-file root.yml --s3-bucket my-bucket --generated-template-file generated-root.yml`

### CLI version used

aws-cli/2.8.2 Python/3.9.11 Windows/10 exe/AMD64 prompt/off

### Environment details (OS name and version, etc.)

Windows 11

**Comment by GasimGasimzada** [comment]
I checked the source code and found a workaround. Instead of directly passing the file to the lambda, I created a directory and put the lambda file in the directory:

```
lambda-pre-signup/lambda-pre-signup.js
```

Then, I pass the directory to the cloudformation:

```yaml
MyPreSignupLambda:
  Type: AWS::Lambda::Function
  Properties:
    Architectures:
      - arm64
    Code: 'lambda-pre-signup/'
    Handler: 'lambda-pre-signup.handler'
    Runtime: nodejs16.x
    PackageType: Zip
    #Role: !GetAtt MyRole.Arn
```

Since I am passing directory to the `Code` field, `package` command will **always** zip it before uploading to S3.
