### ISSUE TITLE
CLI version `>= 2.11.8` converts property values `N, Y, n, y` to booleans `true,false` when using `aws cloudformation package`

### ISSUE THREAD

**Issue by dansor-AZ** [aws/aws-cli#7805]
### Describe the bug

Hi Team,

Recently encountered breaking changes for aws-cli version >= `v2.11.8` when using `aws cloudformation package` command where properties that use values such as `[N, Y, n, y]`. YAML 1.1 converts these values to booleans (`true`, `false`) unless they are surrounded by double quotes `"`.

### Expected Behavior

It shouldn't convert property values such as `[N, Y, n, y]` to boolean, retaining its original value.

### Current Behavior

Property values such as `[N, Y, n, y]` gets converted to boolean `False` OR `True`.

### Reproduction Steps

1. Create a local folder with a template file 
`touch infrastructure.template`
***template content:***
```
PythonFunction:
  Type: AWS::Lambda::Function
  Properties:
    FunctionName: y
    Runtime: python3.8
    Role: !GetAtt LambdaBasicExecutionRole.Arn
    Handler: lambda_function.handler
    Code: lambda/
```
2.  Create a subdirectory named `lambda` within this folder
3. Create a python file for the lambda code named `lambda_function.py`
***code file content:***
```
import json

def lambda_handler(event, context):
    print("value1 = " + event['key1'])
    return event['key1']
```
4. Run the cfn package command
```
aws cloudformation package \
    --template-file infrastructure.template \
    --s3-bucket <SOME_BUCKET_NAME> \
    --s3-prefix cfn-package-deploy \
    --output-template-file infrastructure-packaged.template \
```
5. Check the processed output template file `infrastructure-packaged.template`
```
%YAML 1.1
---
PythonFunction:
  Type: AWS::Lambda::Function
  Properties:
    FunctionName: true
    Description: Python Function to return specific TimeZone time
    Runtime: python3.8
    Role:
      Fn::GetAtt:
      - LambdaBasicExecutionRole
      - Arn
    Handler: lambda_function.handler
    Code: lambda/
```

The function name changes to true as you can see.  If you use [n or N] then it will change to false. [y or Y] then it will change to true.  Prior aws-cli versions 2.11.8 doesn't have this behavior, so I believe this breaking change is due to this particular [commit](https://github.com/aws/aws-cli/pull/7787). 

Additionally, on a dynamo DB table where you specify Attribute definitions. If the type is a number, it will convert that value unintentionally.

For instance, specifying `AttributeType: N` gets converted to `AttributeType: False`. 

### Possible Solution

The current workaround at the moment is either of the following:

* Use aws-cli versions < `2.11.8`
* Use double quotes on the property values `[N, Y, n, y]` e.g. `["N", "Y", "n", "y"]` which doesn't get converted to boolean when packaged.
* Use JSON for your input template

### Additional Information/Context

As per the change log for 2.11.8 seen [here](https://raw.githubusercontent.com/aws/aws-cli/v2/CHANGELOG.rst), this is the [fix](https://github.com/aws/aws-cli/pull/7787) for issue #3991, which I believe introduced this breaking change. 

From changelog:

`bugfix:cloudformation: Fixes `#3991 <https://github.com/aws/aws-cli/issues/3991>`__. Use YAML 1.1 spec in alignment with CloudFormation YAML support.` 

Would love to get an update to fix the breaking change above regarding this new release.

### Questions

1. Can we handle this better on the CFN CLI Side or is this a reality now that we have moved to YAML 1.1?
2. Is there a better work around we can share to the Customer other than manually inputting Double quotes around these values?
3. When can we expect this to be fixed?

### CLI version used

`>= 2.11.8`

### Environment details (OS name and version, etc.)

Doesn't apply.
