### ISSUE TITLE
aws cloudformation package inconsistency zip or direct upload the lambda code

### ISSUE THREAD

**Issue by bplessis-swi** [aws/aws-cli#7852]
### Describe the bug

Hi,

So this one is quite weird, but in certain "configuration" the packaging of a single-file lambda function with cli 2.11.2 still does a direct file upload instead of zipping the file.

### Expected Behavior

Consistent zip-ing of the lambda file whereever it is located

### Current Behavior

I have found 4 "working case" where the packaging correctly zip the file previous to upload on s3:
  1. If the stack file is in the current folder and the lambda code is in the current folder
  2. if the main stack is local, and include a local substack that include a local lambda code file
  3. if the stack file is in the current folder and the lambda code is in a subfolder
  4. if the main stack is local, and include a local substack that include a lambda code file from a subfolder "folder/lambda.py"

And at least three non working one:
  1. If the stack is in a subfolder with the code in the same folder, and packaging as "template-file subfolder/stack.yml"
  2. If the main (local folder for ex) stack depend on a substack in a subfolder with the code in the same folder
  3. if the main stack depend on a substack in a subfolder with the lambda file in a second level subfolder

In all thoses three occurences the package function will upload the file "as-is"

### Reproduction Steps

Create a "super-stack" like this:;

main.yml:
```
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  SubLambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: subfolder/deploy.yml
```

And a substack subfolder/deploy.yml with:
```
AWSTemplateFormatVersion: "2010-09-09"

Resources:
  ...
  LambaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code: ./lambda_function.py
      Handler: 'lambda_function.lambda_handler'
      Role: !GetAtt ExecutionRole.Arn
      Runtime: 'python3.10'
```

If i trigger a package on the super-stack, the cli will upload the lambda_function.py "as-is" (and fail on deploy).

If i trigger a package on subfolder/deploy.yml, the cli will upload the lambda_function.py "as-is"  (and fail on deploy).

If i cd into the subfolder and package "deploy.yml" the cli will correctly upload the  lambda_function.py in a zip file.

If i move "deploy.yml" in the same folder as main.yml, and change the "Code" attribute to "subfolder/lambda_function.py"  the cli will correctly upload the  lambda_function.py in a zip file.

However if i have the following structure:
```
root
├─ main.yml
├─ subfolder/
│   ├─ deploy.yml
│   ├─lambda/
│    │   ├─ lambda_function.py
```
with `Code: lambda/lambda_function.py` in the deploy.yml then we are back to the non working situation were the lambda_function.py is deployed as a standalone file.

### CLI version used

2.11.2

### Environment details (OS name and version, etc.)

MacOS 13.3.1, Python3.11.2
