### ISSUE TITLE
aws is not found inside the justb4/jmeter image container

### ISSUE THREAD

**Issue by Amit-limbasiya** [aws/aws-cli#7950]
### Describe the bug

I am using the justb4/jmeter image to create the container. 
I am modifying the justb4/jmeter image to add the aws-cli installation.
when I do docker-compose up and try to run the aws --version command it is showing error as aws not found.

In other approach that I've mentioned in additional information, I try to keep the justb4/jmeter image as it is and try to write the installation command in the script file which will run as entrypoint file. Still the output remains same, i.e. aws not found.

### Expected Behavior

it should show the output of aws --version

### Current Behavior

It is showing that aws not found.

### Reproduction Steps

Here is the docker compose file.
```
version: '3.4'

services:
  jmeter:
    image: ${DOCKER_REGISTRY-}jmeter--customimage
    build:
      context: .
      dockerfile: JmeterImage/Dockerfile
    volumes: 
    - ./test-scripts:/jmeter/test-scripts
    - ./results:/jmeter/results
 ```
jmeter is the custom image that I have extended from justb4/jmeter image to install the aws-cli in it.
That image code is look like:
```
FROM justb4/jmeter:latest
RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip 
ENTRYPOINT [ "aws.exe","--version" ]
```
Additional i have used services of my API and ms-sql-server in docker container.
It is showing outout as 
exec /usr/local/bin/aws: no such file or directory.

I have navigated to that directory usr/local/bin/aws, there is the reference pointing to another reference and that is pointing to 3rd reference, that ends at usr/local/aws-cli/v2/bin/dist/aws 
that is where the aws file stored.

### Another approach

I have tried another approach where the image of justb4/jmeter is used as it is and i am running the script at the entrypoint which will download the aws-cli.
here is the compose file 
```
  jmeter:
    image: justb4/jmeter:latest
    volumes: 
    - ./test-scripts:/jmeter/test-scripts
    - ./results:/jmeter/results

    entrypoint: ["sh", "-c","/jmeter/test-scripts/entrypoint.sh"]
```
And the entrypoint.sh script looks like:
```
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && \
    ./aws/install && \
    rm awscliv2.zip
/usr/local/bin/aws --version
```

When the container starts it is downloading and installing aws in the container. I can see those files which i have mentioned in above reproduction steps.
Then after at the last line of installation logs it is showing as 
#### **You can now run: /usr/local/bin/aws --version**

As i have run same command in the entrypoint.sh file, but It is showing error as 
#### **/usr/local/bin/aws: not found** 
at the end of the log.

### Note:
same steps are running in wsl linux 20.04 LTS environment and prints the version. that shows it installed successfully.

### CLI version used

trying to download aws-cli/2.11.25 Python/3.11.3 Linux/5.15.90.1-microsoft-standard-WSL2 exe/x86_64.ubuntu.20 prompt/off

### Environment details (OS name and version, etc.)

docker-compose(Linux environment)
