### ISSUE TITLE
Cannot use Cloudformation parameters JSON file for non-string parameters

### ISSUE THREAD

**Issue by TRManderson** [aws/aws-cli#7992]
### Describe the bug

When using parameters with `Type: Number` (I suspect any non-string type), there is no way to set the parameter value via a parameters JSON file without getting an error

### Expected Behavior

There should be some way to specify the value of a parameter that should be a number via the external parameters JSON file, either automatically converting strings to numbers, or accepting numbers in the JSON for the parameters file.

### Current Behavior

When trying to set a parameter value for `aws cloudformation create-stack` and referring to a local JSON file with the parameters, I have one of two options, both fail:

1. Set the `"ParameterValue"` to be a number, in which case this is the incorrect type for the JSON parser and the error is ` Invalid type for parameter Parameters[0].ParameterValue, value: 3, type: <class 'int'>, valid types: <class 'str'>`
2. Set the `"ParameterValue"` to be a string, in which case this is the incorrect type for the parameter itself, and the error is `  An error occurred (ValidationError) when calling the CreateStack operation: Parameter 'NumberParameter' must be a number.`

### Reproduction Steps

template.yml:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Description: Minimal example
Parameters:
  NumberParameter:
    Type: Number
    Default: 0
    Description: Should be a number
Outputs:
  Example:
    Value:
      Ref: NumberParameter
```

parameters.json:

```json
[{"ParameterKey": "NumberParameter", "ParameterValue": "3"}]
```

Command:

```sh
aws cloudformation create-stack --stack-name bug-test --template-body file://template.yml --parameters file://parameters.json
```

### CLI version used

2.9.16, 2.12.1

### Environment details (OS name and version, etc.)

Ubuntu 20.04, MacOS 13.04
