### ISSUE TITLE
AWS CLI v2.13.0 - Template format error: Unrecognized resource types: [AWS::OSIS::Pipeline]

### ISSUE THREAD

**Issue by antoineaws** [aws/aws-cli#8032]
### Describe the bug

Team, 

Cloudformation is showing an error `Template format error: Unrecognized resource types: [AWS::OSIS::Pipeline]` in the latest version even though in previous versions it seems that we added this resource.

Template example:
```yaml
Resources:
  OpenSearchIngestionPipeline:
    Type: AWS::OSIS::Pipeline
    Properties:
      LogPublishingOptions:
        IsLoggingEnabled: true
        CloudWatchLogDestination:
          LogGroup: "/aws/vendedlogs/test-pipeline"
      MinUnits: 3
      MaxUnits: 9
      PipelineConfigurationBody:
        Value: |
            This is a multi-line value
            that spans multiple lines
            in YAML format
      PipelineName: test-pipeline
Outputs:
  PipelineArn:
    Value:
      Ref: OpenSearchIngestionPipeline
  IngestEndpointUrls:
    Value:
      Ref: OpenSearchIngestionPipeline
```

### Expected Behavior

Expecting the pipeline to be provisionned

### Current Behavior

Error: 
> An error occurred (ValidationError) when calling the CreateChangeSet operation: Template format error: Unrecognized resource types: [AWS::OSIS::Pipeline]

### Reproduction Steps

Use the above template and execute a cloudformation deploy:
`aws cloudformation deploy --template-file resource.yaml --stack-name demo`

### CLI version used

aws-cli/2.13.0 Python/3.11.4 Darwin/22.5.0 exe/x86_64 prompt/off

### Environment details (OS name and version, etc.)

MacOS Ventura 13.4
