### ISSUE TITLE
Create SSM Document of type CloudFormation fails

### ISSUE THREAD

**Issue by takesson** [aws/aws-cli#8253]
### Describe the bug

This command should create an SSM Document according to the below documentation:
`aws ssm create-document --name "cfn-codebuild-bogus-application-5.2" --document-type "CloudFormation" --document-format YAML --content file://cfn-codebuild-bogus-application.yml --region eu-west-1`

https://docs.aws.amazon.com/systems-manager/latest/userguide/application-manager-working-templates-overview.html#application-manager-working-stacks-creating-template

### Expected Behavior

Create an SSM Document containing the CloudFormation template.

Pasting exactly the same template into the Console works, but that has to be the Application Manager template library (seems unsupported in SSM Documents).

### Current Behavior

`An error occurred (InvalidDocumentContent) when calling the CreateDocument operation: [message: "object has missing required properties ([\"schemaVersion\",\"templateBody\"])" - parent node: /]`

### Reproduction Steps

Get the sample YAML template from here:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/template-formats.html

`aws ssm create-document --name "cfn-codebuild-bogus-application-5.2" --document-type "CloudFormation" --document-format YAML --content file://cfn-codebuild-bogus-application.yml --region eu-west-1`

### CLI version used

2.13.27

### Environment details (OS name and version, etc.)

macOS Python/3.11.6 Darwin/21.6.0

**Comment by takesson** [comment]
Same error when updating a document which already exists (created manually in Console).

`aws ssm update-document --name "cfn-codebuild-bogus-application-5.2" --document-version "\$LATEST" --content file://cfn-codebuild-bogus-application.yml --region eu-west-1 `

**Comment by aBurmeseDev** [comment]
Hi @takesson - thanks for reaching out. 

According to the error, it sounds like the document content yaml is missing some of the required properties `schemaVersion` `templateBody` and the error is being thrown from [service side](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_CreateDocument.html#API_CreateDocument_Errors) rather than CLI. If you could share the yaml file for verification, I could reach out to service team on your behalf to verify. Please make sure any sensitive info are redacted. 

Here's documentation on [writing SSM document content](https://docs.aws.amazon.com/systems-manager/latest/userguide/documents-creating-content.html#writing-ssm-doc-content) and [creating an SSM document](https://docs.aws.amazon.com/systems-manager/latest/userguide/documents-using.html#create-ssm-document-cli) for reference.

Also note that you'll need to install and configure the AWS CLI or the AWS Tools for PowerShell in order to run create SSM document with command line.

Hope that helps!

**Comment by takesson** [comment]
Thanks for looking into the issue. I have done some more investigation.

Most of the SSM document types are entirely new formats (Command, Automation, Session, ...) but Cloudformation had its template format since way back and there is tooling support for that format (cfn-lint, VS Code, other IDEs, ...). The Cfn templates must consequently be authored and SCM-versioned in Cfn format, not wrapped into an SSM document.

The problem here is that I was not aware that the Cfn template had to be wrapped into an SSM document. The person writing the AWS documentation did not document that important step or did actually expect the CLI / service to take care of the wrapping. It would be helpful to avoid every builder having to develop the script to wrap Cfn template into SSM document themselves.

Suggestions:
* CLI takes care of wrapping the Cfn template into yml or json on the fly. This would be ideal.
* The SSM documentation provides a working example of using CLI based on a Cfn template, i.e. provides a sample script doing the wrapping.

I used this sample Cfn template when testing (from one of the above documentation links):
```
AWSTemplateFormatVersion: "2010-09-09"
Description: A sample template
Resources:
  MyEC2Instance: #An inline comment
    Type: "AWS::EC2::Instance"
    Properties: 
      ImageId: "ami-0ff8a91507f77f867" #Another comment -- This is a Linux AMI
      InstanceType: t2.micro
      KeyName: testkey
      BlockDeviceMappings:
        -
          DeviceName: /dev/sdm
          Ebs:
            VolumeType: io1
            Iops: 200
            DeleteOnTermination: false
            VolumeSize: 20
```
