### ISSUE TITLE
validate-template fails to identify AWS::CloudFormation::Stack Properties TemplateBody as invalid

### ISSUE THREAD

**Issue by sparr** [aws/aws-cli#8412]
### Describe the bug

The following template validates successfully, but then fails during `create-stack` due to `Encountered unsupported property TemplateBody`. Other more-obviously-invalid property names like `foo` produce expected validation failures.

### Expected Behavior

Validation failure

### Current Behavior

Successful validation

### Reproduction Steps

aws cloudformation validate-template --template-body file://thefollowingfile.yaml

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TestStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody:
        AWSTemplateFormatVersion: '2010-09-09'
```

### CLI version used

aws-cli/2.14.4

### Environment details (OS name and version, etc.)

Python/3.11.6 Darwin/23.1.0 MacOS/14.1
