### ISSUE TITLE
cloudformation deploy fails when using SSM Advanced Parameter Share ARN

### ISSUE THREAD

**Issue by lmayorga1980** [aws/aws-cli#8595]
### Describe the bug

Trying to use the consume the new ssm advanced parameter sharing

```
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      # Other EC2 properties...
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash
            echo "${MyParameter}"
Parameters:
  MyParameter:
    Description: SSM parameter value
    Type: 'AWS::SSM::Parameter::Value<String>'
    Default: 'arn:aws:ssm:REGION:SOURCE_ACCOUNT_ID:parameter/PARAMETER_NAME'
```

### Expected Behavior

It should create the instance using the AMI value from the SSM Shared Parameter from Cross Account.

 

### Current Behavior

`An error ocurred (Internal Failure) when calling the CreateChangeSet operation (reached max retries: 2) Unknown`

### Reproduction Steps

1. Create an SSM Advanced Parameter in AWS Account A with a Value equal to an existing AMI ID
2. Share the SSM Parameter using RAM and grant access to AWS Account B
3. Create a CF Template similar to the provided one in order to launch a simple instance - This is just to verify the launch of the appropriate AMI ID
4. Run `aws cloudformation depoy <template>`

### CLI version used

2.15.x

### Environment details (OS name and version, etc.)

Mac OS Sonoma 14.4
