### ISSUE TITLE
`GLIBC_2.28' not found with aws-actions/configure-aws-credentials@v4 action

### ISSUE THREAD

**Issue by DimuthuSig** [aws/aws-cli#8779]
### Describe the bug

The action aws-actions/configure-aws-credentials@v4 fails with the error ```/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)```

### Expected Behavior

Authenticate with assumed role.

### Current Behavior

Action fails immediately when running within the amazon/aws-cli:latest container.

### Reproduction Steps

Add a Github actions run similar to the following
```
jobs:

  ecr_login:
    name: Login to ECR
    runs-on: medium
    container:
      image: amazon/aws-cli
    steps:
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: some-role
```

### Possible Solution

nvm version

### CLI version used

2.17.7

### Environment details (OS name and version, etc.)

amazon-eks-node-1.28-v20240605
