### ISSUE TITLE
Cannot install awscli in GitHub Action

### ISSUE THREAD

**Issue by patrickpasquini** [aws/aws-cli#8978]
### Describe the bug

When running the GitHub Action script that executes the command `sudo apt-get install awscli`, I encounter an error.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

The command is expected to execute normally.

### Current Behavior

 I am receiving the following error:
 
```
Package awscli is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'awscli' has no installation candidate
```

### Reproduction Steps

```
runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{github.ref_name}}
        
    - name: Install AWS CLI
      run: |
        sudo apt-get update
        sudo apt-get install awscli
```

### CLI version used

latest

### Environment details (OS name and version, etc.)

ubuntu-latest
