### ISSUE TITLE
`aws eks update-kubeconfig` does not persist AWS_CONFIG_FILE

### ISSUE THREAD

**Issue by lcmgh** [aws/aws-cli#9428]
### Describe the bug

```bash
AWS_CONFIG_FILE=abc
aws eks update-kubeconfig --profile custom-profile --region eu-central-1 --name cluster-name --alias custom-alias
```

adds to `~/.kube/config`:

```yml
- name: arn:aws:eks:eu-central-1:xxxxxxx:cluster/abc-prod
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-central-1 
      - eks
      - get-token
      - --cluster-name
      - cluster-name
      - --output
      - json
      command: aws
      env:
      - name: AWS_PROFILE
        value: custom-profile
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

is setting `AWS_PROFILE` as env var but not `AWS_CONFIG_FILE` which makes the AWS_PROFILE env var point to a wrong or not-existing profile if follow up commands do not specify AWS_CONFIG_FILE.  I am using [kube](https://docs.rs/crate/kube/0.99.0) which is a library to access k8s that relies on a kubeconfig file for that I cannot set any AWS_CONFIG_FILE vars.

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Persistance of
AWS_CONFIG_FILE env var

```yml
  env:
  - name: AWS_CONFIG_FILE
    value: abc
```

### Current Behavior

Not persisting AWS_CONFIG_FILE var.

### Reproduction Steps

See above.

### CLI version used

aws-cli/2.25.11 Python/3.12.9 Darwin/23.5.0 source/arm64

### Environment details (OS name and version, etc.)

mac os

**Comment by adev-code** [comment]
Hello @lcmgh, thanks for reaching out. I have replicated the issue and got the same. However I have tried two solutions and they worked. Could you try:
1. Set environment variables manually set the environment variables every time you run `kubectl`. By prefixing your `kubectl`commands with `AWS_CONFIG_FILE=~/path/to/custom-config AWS_SHARED_CREDENTIALS_FILE=~/path/to/custom-credentials` , you ensure `kubectl` can find your custom AWS configuration. Take note that this is on every command.
2. Meanwhile, The second solution involves directly modifying the `kubeconfig` file to include the missing environment variables. After running `aws eks update-kubeconfig`, you edit the generated `~/.kube/config file` to add the `AWS_CONFIG_FILE` and `AWS_SHARED_CREDENTIALS_FILE` variables to the `env` section. Instead of having just `AWS_PROFILE` in the `env` section, you'll add entries for the other necessary environment variables, ensuring `kubectl` and other tools can find your custom AWS configuration files without requiring you to set these variables on every command.
My modified `kubeconfig` file implementing solution 2:

```
clusters:
- cluster:
    server: https://example-cluster.eks.amazonaws.com
  name: test-cluster
contexts:
- context:
    cluster: test-cluster
    user: test-user
  name: test-context
current-context: test-context
kind: Config
preferences: {}
users:
- name: test-user
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-central-1
      - eks
      - get-token
      - --cluster-name
      - test-cluster
      - --output
      - json
      command: /home/ec2-user/eks-test/test-env.sh
      env:
      - name: AWS_PROFILE
        value: custom-profile
      - name: AWS_CONFIG_FILE
        value: /home/ec2-user/eks-test/custom-aws-config
      - name: AWS_SHARED_CREDENTIALS_FILE
        value: /home/ec2-user/eks-test/custom-aws-credentials
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
Please let me know if you have any questions. Thanks.
